///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PDS_NS.Recording_Modules.LoginLogoff
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The NS_SwitchUser recording.
    /// </summary>
    [TestModule("2ef97a32-dc05-4352-8475-10e0badefba0", ModuleType.Recording, 1)]
    public partial class NS_SwitchUser : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::PDS_NS.PDS_NSRepository repository.
        /// </summary>
        public static global::PDS_NS.PDS_NSRepository repo = global::PDS_NS.PDS_NSRepository.Instance;

        static NS_SwitchUser instance = new NS_SwitchUser();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public NS_SwitchUser()
        {
            userId = "";
            password = "";
            closeForms = "False";
            expectedFeedback = "";
            role = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static NS_SwitchUser Instance
        {
            get { return instance; }
        }

#region Variables

        string _userId;

        /// <summary>
        /// Gets or sets the value of variable userId.
        /// </summary>
        [TestVariable("858e3d91-57e6-4e1f-ae04-31929af622b3")]
        public string userId
        {
            get { return _userId; }
            set { _userId = value; }
        }

        string _password;

        /// <summary>
        /// Gets or sets the value of variable password.
        /// </summary>
        [TestVariable("0083a705-2ccc-46d1-bdd0-4a33cdc4ca26")]
        public string password
        {
            get { return _password; }
            set { _password = value; }
        }

        string _closeForms;

        /// <summary>
        /// Gets or sets the value of variable closeForms.
        /// </summary>
        [TestVariable("5d4cd189-f927-46f5-8b42-304b492808aa")]
        public string closeForms
        {
            get { return _closeForms; }
            set { _closeForms = value; }
        }

        string _expectedFeedback;

        /// <summary>
        /// Gets or sets the value of variable expectedFeedback.
        /// </summary>
        [TestVariable("8101a6b5-997b-441b-99b8-2768788c544a")]
        public string expectedFeedback
        {
            get { return _expectedFeedback; }
            set { _expectedFeedback = value; }
        }

        string _role;

        /// <summary>
        /// Gets or sets the value of variable role.
        /// </summary>
        [TestVariable("579c1b59-b7c2-4b01-92df-f1ffcfde557e")]
        public string role
        {
            get { return _role; }
            set { _role = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            UserCodeCollections.NS_LogonLogoff.NS_SwitchUserFunction(userId, password, role, expectedFeedback, ValueConverter.ArgumentFromString<bool>("closeForms", closeForms));
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
