///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PDS_NS.Recording_Modules.Trains
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CreatePTCLabTrainIfDoesntExist recording.
    /// </summary>
    [TestModule("a3abd2b4-07f7-44db-a24e-f324ceb198b4", ModuleType.Recording, 1)]
    public partial class CreatePTCLabTrainIfDoesntExist : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::PDS_NS.PDS_NSRepository repository.
        /// </summary>
        public static global::PDS_NS.PDS_NSRepository repo = global::PDS_NS.PDS_NSRepository.Instance;

        static CreatePTCLabTrainIfDoesntExist instance = new CreatePTCLabTrainIfDoesntExist();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CreatePTCLabTrainIfDoesntExist()
        {
            engineConsist_reportingPassCount = "";
            engineConsist_reportingLocation = "";
            engineConsist_reportingSource = "";
            engineConsist_helperCrewPoolID = "";
            engineConsist_assignedDivision = "";
            engineSeeds = "";
            trainConsist_hazmatConstraintRecord = "";
            trainConsist_maxCarWidthConstraintRecord = "";
            trainConsist_maxCarHeightConstraintRecord = "";
            trainConsist_maxCarWeightConstraintRecord = "";
            trainConsist_speedClass = "";
            trainConsist_totalBrakingForce = "";
            trainConsist_operativeBrakes = "";
            trainConsist_axles = "";
            trainConsist_trainLength = "";
            trainConsist_trailingTonnage = "";
            trainConsist_numberOfEmpties = "";
            trainConsist_numberOfLoads = "";
            trainConsist_maxPlateSize = "";
            trainConsist_tihConstraintRecord = "";
            trainConsist_reportingSource = "";
            trainConsist_reportingPassCount = "";
            trainConsist_reportingLocation = "";
            consistSeed = "";
            trainSegment_trainDestination = "";
            trainSegment_trainOrigin = "";
            trainSegment_timeType = "";
            trainSegment_timeZone = "";
            trainSegment_timeOffsetMinutes = "";
            trainSegment_dateOffsetDays = "";
            trainSegment_effectivePasscount = "";
            trainSegment_effectiveLocation = "";
            schedule_stations = "";
            schedule_trainDestination = "";
            schedule_trainOrigin = "";
            schedule_trainGroup = "";
            schedule_trainCategory = "";
            schedule_reportType = "";
            trainSeed = "";
            misOrManual = "";
            engineConsist_defaultDataApplied = "";
            engineConsist_purpose = "";
            engineConsist_engines = "";
            hostname = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CreatePTCLabTrainIfDoesntExist Instance
        {
            get { return instance; }
        }

#region Variables

        string _engineConsist_reportingPassCount;

        /// <summary>
        /// Gets or sets the value of variable engineConsist_reportingPassCount.
        /// </summary>
        [TestVariable("f8a701bc-8e6d-4c47-8bd2-71976738ff69")]
        public string engineConsist_reportingPassCount
        {
            get { return _engineConsist_reportingPassCount; }
            set { _engineConsist_reportingPassCount = value; }
        }

        string _engineConsist_reportingLocation;

        /// <summary>
        /// Gets or sets the value of variable engineConsist_reportingLocation.
        /// </summary>
        [TestVariable("ad50542e-13e7-4d26-9609-fd3efc291344")]
        public string engineConsist_reportingLocation
        {
            get { return _engineConsist_reportingLocation; }
            set { _engineConsist_reportingLocation = value; }
        }

        string _engineConsist_reportingSource;

        /// <summary>
        /// Gets or sets the value of variable engineConsist_reportingSource.
        /// </summary>
        [TestVariable("50832cd1-3cfc-4fc1-a5f1-9fb88f64cc65")]
        public string engineConsist_reportingSource
        {
            get { return _engineConsist_reportingSource; }
            set { _engineConsist_reportingSource = value; }
        }

        string _engineConsist_helperCrewPoolID;

        /// <summary>
        /// Gets or sets the value of variable engineConsist_helperCrewPoolID.
        /// </summary>
        [TestVariable("1812b7c3-7aa3-4a54-994b-4962385b4850")]
        public string engineConsist_helperCrewPoolID
        {
            get { return _engineConsist_helperCrewPoolID; }
            set { _engineConsist_helperCrewPoolID = value; }
        }

        string _engineConsist_assignedDivision;

        /// <summary>
        /// Gets or sets the value of variable engineConsist_assignedDivision.
        /// </summary>
        [TestVariable("be25ecb2-4869-41fe-86e0-a08d0e12d938")]
        public string engineConsist_assignedDivision
        {
            get { return _engineConsist_assignedDivision; }
            set { _engineConsist_assignedDivision = value; }
        }

        string _engineSeeds;

        /// <summary>
        /// Gets or sets the value of variable engineSeeds.
        /// </summary>
        [TestVariable("6d2ce154-1f1a-4dc2-9037-90b91c440c81")]
        public string engineSeeds
        {
            get { return _engineSeeds; }
            set { _engineSeeds = value; }
        }

        string _trainConsist_hazmatConstraintRecord;

        /// <summary>
        /// Gets or sets the value of variable trainConsist_hazmatConstraintRecord.
        /// </summary>
        [TestVariable("a7bf7c0f-554e-41a7-a7f6-57ffd3052648")]
        public string trainConsist_hazmatConstraintRecord
        {
            get { return _trainConsist_hazmatConstraintRecord; }
            set { _trainConsist_hazmatConstraintRecord = value; }
        }

        string _trainConsist_maxCarWidthConstraintRecord;

        /// <summary>
        /// Gets or sets the value of variable trainConsist_maxCarWidthConstraintRecord.
        /// </summary>
        [TestVariable("2a3fe86c-7a80-4b77-a978-7f069441b06d")]
        public string trainConsist_maxCarWidthConstraintRecord
        {
            get { return _trainConsist_maxCarWidthConstraintRecord; }
            set { _trainConsist_maxCarWidthConstraintRecord = value; }
        }

        string _trainConsist_maxCarHeightConstraintRecord;

        /// <summary>
        /// Gets or sets the value of variable trainConsist_maxCarHeightConstraintRecord.
        /// </summary>
        [TestVariable("5861310b-a0eb-47ad-83a5-b821e8c86d7a")]
        public string trainConsist_maxCarHeightConstraintRecord
        {
            get { return _trainConsist_maxCarHeightConstraintRecord; }
            set { _trainConsist_maxCarHeightConstraintRecord = value; }
        }

        string _trainConsist_maxCarWeightConstraintRecord;

        /// <summary>
        /// Gets or sets the value of variable trainConsist_maxCarWeightConstraintRecord.
        /// </summary>
        [TestVariable("e4d8f4c8-e4ea-4def-bb54-d98e74db5bee")]
        public string trainConsist_maxCarWeightConstraintRecord
        {
            get { return _trainConsist_maxCarWeightConstraintRecord; }
            set { _trainConsist_maxCarWeightConstraintRecord = value; }
        }

        string _trainConsist_speedClass;

        /// <summary>
        /// Gets or sets the value of variable trainConsist_speedClass.
        /// </summary>
        [TestVariable("5e6bceda-f6fd-4308-8062-49f0bce78930")]
        public string trainConsist_speedClass
        {
            get { return _trainConsist_speedClass; }
            set { _trainConsist_speedClass = value; }
        }

        string _trainConsist_totalBrakingForce;

        /// <summary>
        /// Gets or sets the value of variable trainConsist_totalBrakingForce.
        /// </summary>
        [TestVariable("c645b406-d005-47f5-8dce-4ac38e80b35d")]
        public string trainConsist_totalBrakingForce
        {
            get { return _trainConsist_totalBrakingForce; }
            set { _trainConsist_totalBrakingForce = value; }
        }

        string _trainConsist_operativeBrakes;

        /// <summary>
        /// Gets or sets the value of variable trainConsist_operativeBrakes.
        /// </summary>
        [TestVariable("a5defd7a-465b-4d96-a068-acc5ff9493e3")]
        public string trainConsist_operativeBrakes
        {
            get { return _trainConsist_operativeBrakes; }
            set { _trainConsist_operativeBrakes = value; }
        }

        string _trainConsist_axles;

        /// <summary>
        /// Gets or sets the value of variable trainConsist_axles.
        /// </summary>
        [TestVariable("c841d835-ab81-4b3e-801e-f3fd46cd9d4f")]
        public string trainConsist_axles
        {
            get { return _trainConsist_axles; }
            set { _trainConsist_axles = value; }
        }

        string _trainConsist_trainLength;

        /// <summary>
        /// Gets or sets the value of variable trainConsist_trainLength.
        /// </summary>
        [TestVariable("0c9875cc-c16d-4e70-91f3-4f92445d4426")]
        public string trainConsist_trainLength
        {
            get { return _trainConsist_trainLength; }
            set { _trainConsist_trainLength = value; }
        }

        string _trainConsist_trailingTonnage;

        /// <summary>
        /// Gets or sets the value of variable trainConsist_trailingTonnage.
        /// </summary>
        [TestVariable("21873ba4-e5d3-4a33-bfc5-e3831bd70549")]
        public string trainConsist_trailingTonnage
        {
            get { return _trainConsist_trailingTonnage; }
            set { _trainConsist_trailingTonnage = value; }
        }

        string _trainConsist_numberOfEmpties;

        /// <summary>
        /// Gets or sets the value of variable trainConsist_numberOfEmpties.
        /// </summary>
        [TestVariable("1eb78e5b-c5fa-413a-bcfd-fe42a5023183")]
        public string trainConsist_numberOfEmpties
        {
            get { return _trainConsist_numberOfEmpties; }
            set { _trainConsist_numberOfEmpties = value; }
        }

        string _trainConsist_numberOfLoads;

        /// <summary>
        /// Gets or sets the value of variable trainConsist_numberOfLoads.
        /// </summary>
        [TestVariable("67d13c76-d395-4b1e-88ed-2d3ac15d45e7")]
        public string trainConsist_numberOfLoads
        {
            get { return _trainConsist_numberOfLoads; }
            set { _trainConsist_numberOfLoads = value; }
        }

        string _trainConsist_maxPlateSize;

        /// <summary>
        /// Gets or sets the value of variable trainConsist_maxPlateSize.
        /// </summary>
        [TestVariable("9ab52ea3-a52f-49ae-ae23-1a6a8113ceb9")]
        public string trainConsist_maxPlateSize
        {
            get { return _trainConsist_maxPlateSize; }
            set { _trainConsist_maxPlateSize = value; }
        }

        string _trainConsist_tihConstraintRecord;

        /// <summary>
        /// Gets or sets the value of variable trainConsist_tihConstraintRecord.
        /// </summary>
        [TestVariable("663f0487-ef21-47d6-b7e5-0a82bd494209")]
        public string trainConsist_tihConstraintRecord
        {
            get { return _trainConsist_tihConstraintRecord; }
            set { _trainConsist_tihConstraintRecord = value; }
        }

        string _trainConsist_reportingSource;

        /// <summary>
        /// Gets or sets the value of variable trainConsist_reportingSource.
        /// </summary>
        [TestVariable("abb0534d-4ab8-4186-a341-8706c3e4989b")]
        public string trainConsist_reportingSource
        {
            get { return _trainConsist_reportingSource; }
            set { _trainConsist_reportingSource = value; }
        }

        string _trainConsist_reportingPassCount;

        /// <summary>
        /// Gets or sets the value of variable trainConsist_reportingPassCount.
        /// </summary>
        [TestVariable("35f6d8e7-8731-4ca1-b3cc-5895a39804c6")]
        public string trainConsist_reportingPassCount
        {
            get { return _trainConsist_reportingPassCount; }
            set { _trainConsist_reportingPassCount = value; }
        }

        string _trainConsist_reportingLocation;

        /// <summary>
        /// Gets or sets the value of variable trainConsist_reportingLocation.
        /// </summary>
        [TestVariable("b33eded4-4f2f-43e3-af19-e392fdc67d66")]
        public string trainConsist_reportingLocation
        {
            get { return _trainConsist_reportingLocation; }
            set { _trainConsist_reportingLocation = value; }
        }

        string _consistSeed;

        /// <summary>
        /// Gets or sets the value of variable consistSeed.
        /// </summary>
        [TestVariable("e4659834-71ca-4e8a-8c10-f784c23c6b68")]
        public string consistSeed
        {
            get { return _consistSeed; }
            set { _consistSeed = value; }
        }

        string _trainSegment_trainDestination;

        /// <summary>
        /// Gets or sets the value of variable trainSegment_trainDestination.
        /// </summary>
        [TestVariable("10c40ae4-ad6d-4c68-9816-c15e8dc0ded2")]
        public string trainSegment_trainDestination
        {
            get { return _trainSegment_trainDestination; }
            set { _trainSegment_trainDestination = value; }
        }

        string _trainSegment_trainOrigin;

        /// <summary>
        /// Gets or sets the value of variable trainSegment_trainOrigin.
        /// </summary>
        [TestVariable("a5e50d7e-c0d4-47b6-9308-4249f537dca1")]
        public string trainSegment_trainOrigin
        {
            get { return _trainSegment_trainOrigin; }
            set { _trainSegment_trainOrigin = value; }
        }

        string _trainSegment_timeType;

        /// <summary>
        /// Gets or sets the value of variable trainSegment_timeType.
        /// </summary>
        [TestVariable("b23d4180-da14-469e-b3a1-61f455631057")]
        public string trainSegment_timeType
        {
            get { return _trainSegment_timeType; }
            set { _trainSegment_timeType = value; }
        }

        string _trainSegment_timeZone;

        /// <summary>
        /// Gets or sets the value of variable trainSegment_timeZone.
        /// </summary>
        [TestVariable("f099a31c-e335-4d3c-8ee4-84e6b27b6ae3")]
        public string trainSegment_timeZone
        {
            get { return _trainSegment_timeZone; }
            set { _trainSegment_timeZone = value; }
        }

        string _trainSegment_timeOffsetMinutes;

        /// <summary>
        /// Gets or sets the value of variable trainSegment_timeOffsetMinutes.
        /// </summary>
        [TestVariable("95c1300a-4634-4cd3-b03f-bd18d08d16d3")]
        public string trainSegment_timeOffsetMinutes
        {
            get { return _trainSegment_timeOffsetMinutes; }
            set { _trainSegment_timeOffsetMinutes = value; }
        }

        string _trainSegment_dateOffsetDays;

        /// <summary>
        /// Gets or sets the value of variable trainSegment_dateOffsetDays.
        /// </summary>
        [TestVariable("501afdab-ab62-4092-a873-bed4c7f71462")]
        public string trainSegment_dateOffsetDays
        {
            get { return _trainSegment_dateOffsetDays; }
            set { _trainSegment_dateOffsetDays = value; }
        }

        string _trainSegment_effectivePasscount;

        /// <summary>
        /// Gets or sets the value of variable trainSegment_effectivePasscount.
        /// </summary>
        [TestVariable("c649a6b3-593c-44ea-a769-650303d7d006")]
        public string trainSegment_effectivePasscount
        {
            get { return _trainSegment_effectivePasscount; }
            set { _trainSegment_effectivePasscount = value; }
        }

        string _trainSegment_effectiveLocation;

        /// <summary>
        /// Gets or sets the value of variable trainSegment_effectiveLocation.
        /// </summary>
        [TestVariable("b0d94189-a938-46f9-aecb-fed3b1237251")]
        public string trainSegment_effectiveLocation
        {
            get { return _trainSegment_effectiveLocation; }
            set { _trainSegment_effectiveLocation = value; }
        }

        string _schedule_stations;

        /// <summary>
        /// Gets or sets the value of variable schedule_stations.
        /// </summary>
        [TestVariable("81872a77-3915-49f2-aae3-f922e397587e")]
        public string schedule_stations
        {
            get { return _schedule_stations; }
            set { _schedule_stations = value; }
        }

        string _schedule_trainDestination;

        /// <summary>
        /// Gets or sets the value of variable schedule_trainDestination.
        /// </summary>
        [TestVariable("f4a3f34f-a859-43d5-a254-34cf6eeb1fd1")]
        public string schedule_trainDestination
        {
            get { return _schedule_trainDestination; }
            set { _schedule_trainDestination = value; }
        }

        string _schedule_trainOrigin;

        /// <summary>
        /// Gets or sets the value of variable schedule_trainOrigin.
        /// </summary>
        [TestVariable("e1b273e6-2521-4989-9887-bd0b5e1f70df")]
        public string schedule_trainOrigin
        {
            get { return _schedule_trainOrigin; }
            set { _schedule_trainOrigin = value; }
        }

        string _schedule_trainGroup;

        /// <summary>
        /// Gets or sets the value of variable schedule_trainGroup.
        /// </summary>
        [TestVariable("54a86c1e-8101-4491-b6a5-dfa21bfda306")]
        public string schedule_trainGroup
        {
            get { return _schedule_trainGroup; }
            set { _schedule_trainGroup = value; }
        }

        string _schedule_trainCategory;

        /// <summary>
        /// Gets or sets the value of variable schedule_trainCategory.
        /// </summary>
        [TestVariable("93bb5f2d-758e-4c92-a20a-ea5351e4f5a5")]
        public string schedule_trainCategory
        {
            get { return _schedule_trainCategory; }
            set { _schedule_trainCategory = value; }
        }

        string _schedule_reportType;

        /// <summary>
        /// Gets or sets the value of variable schedule_reportType.
        /// </summary>
        [TestVariable("25519528-da92-4f38-9a59-02f57824b84e")]
        public string schedule_reportType
        {
            get { return _schedule_reportType; }
            set { _schedule_reportType = value; }
        }

        string _trainSeed;

        /// <summary>
        /// Gets or sets the value of variable trainSeed.
        /// </summary>
        [TestVariable("9e6ab0e9-cc13-46c2-b1ee-1615f5fcb494")]
        public string trainSeed
        {
            get { return _trainSeed; }
            set { _trainSeed = value; }
        }

        string _misOrManual;

        /// <summary>
        /// Gets or sets the value of variable misOrManual.
        /// </summary>
        [TestVariable("f169300a-e104-4a97-a299-70dd23ef5929")]
        public string misOrManual
        {
            get { return _misOrManual; }
            set { _misOrManual = value; }
        }

        string _engineConsist_defaultDataApplied;

        /// <summary>
        /// Gets or sets the value of variable engineConsist_defaultDataApplied.
        /// </summary>
        [TestVariable("dcd94710-8bae-49d1-a31f-c307cd340575")]
        public string engineConsist_defaultDataApplied
        {
            get { return _engineConsist_defaultDataApplied; }
            set { _engineConsist_defaultDataApplied = value; }
        }

        string _engineConsist_purpose;

        /// <summary>
        /// Gets or sets the value of variable engineConsist_purpose.
        /// </summary>
        [TestVariable("23ffff71-2ae0-43ea-a64d-20bf0b245499")]
        public string engineConsist_purpose
        {
            get { return _engineConsist_purpose; }
            set { _engineConsist_purpose = value; }
        }

        string _engineConsist_engines;

        /// <summary>
        /// Gets or sets the value of variable engineConsist_engines.
        /// </summary>
        [TestVariable("850ca122-acff-43bd-a8aa-122c1d6aef9d")]
        public string engineConsist_engines
        {
            get { return _engineConsist_engines; }
            set { _engineConsist_engines = value; }
        }

        string _hostname;

        /// <summary>
        /// Gets or sets the value of variable hostname.
        /// </summary>
        [TestVariable("56e37618-0bba-47a6-a6ee-9962624a457e")]
        public string hostname
        {
            get { return _hostname; }
            set { _hostname = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            UserCodeCollections.NS_LabTrains.CreatePTCLabTrainIfDoesNotExist_Trainsheet_MIS(misOrManual, trainSeed, schedule_reportType, schedule_trainCategory, schedule_trainGroup, schedule_trainOrigin, schedule_trainDestination, schedule_stations, trainSegment_effectiveLocation, trainSegment_effectivePasscount, trainSegment_dateOffsetDays, trainSegment_timeOffsetMinutes, trainSegment_timeZone, trainSegment_timeType, trainSegment_trainOrigin, trainSegment_trainDestination, consistSeed, trainConsist_reportingLocation, trainConsist_reportingPassCount, trainConsist_reportingSource, trainConsist_tihConstraintRecord, trainConsist_maxPlateSize, trainConsist_numberOfLoads, trainConsist_numberOfEmpties, trainConsist_trailingTonnage, trainConsist_trainLength, trainConsist_axles, trainConsist_operativeBrakes, trainConsist_totalBrakingForce, trainConsist_speedClass, trainConsist_maxCarWeightConstraintRecord, trainConsist_maxCarHeightConstraintRecord, trainConsist_maxCarWidthConstraintRecord, trainConsist_hazmatConstraintRecord, engineSeeds, engineConsist_assignedDivision, engineConsist_helperCrewPoolID, engineConsist_reportingSource, engineConsist_reportingLocation, engineConsist_reportingPassCount, engineConsist_defaultDataApplied, engineConsist_purpose, engineConsist_engines, hostname);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
