//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a buildPTCMessages.py.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.IO;
using System.Xml;
using System.Xml.Serialization;
using System.Collections;
using STE.Code_Utils.messages;

namespace STE.Code_Utils.messages.PTC
{
    public partial class PTC_DC_MESS_2 {
        private PTC_DC_MESSHEADER_2 thisHEADER;
        private PTC_DC_MESSCONTENT_2 thisCONTENT;

        public PTC_DC_MESSHEADER_2 HEADER {
            get { return this.thisHEADER; }
            set { this.thisHEADER = value; }
        }

        public PTC_DC_MESSCONTENT_2 CONTENT {
            get { return this.thisCONTENT; }
            set { this.thisCONTENT = value; }
        }

        public static PTC_DC_MESS_2 fromSerializableObject(DC_MESS_2 message) {
            PTC_DC_MESS_2 dc_mess_2 = new PTC_DC_MESS_2();
            DC_MESSHEADER_2 header = null;
            DC_MESSCONTENT_2 content = null;
            if (message.Items.Length == 1) {
                content = (DC_MESSCONTENT_2) message.Items[0];
            }
            else {
                header = (DC_MESSHEADER_2) message.Items[0];
                content = (DC_MESSCONTENT_2) message.Items[1];
            }

            if (header != null) {
                PTC_DC_MESSHEADER_2 head = new PTC_DC_MESSHEADER_2();
                if (header.HEADER_EVENT_DATE != null && header.HEADER_EVENT_DATE.Length > 0) {
                    head.HEADER_EVENT_DATE = header.HEADER_EVENT_DATE[0].Value;
                }

                if (header.HEADER_EVENT_TIME != null && header.HEADER_EVENT_TIME.Length > 0) {
                    head.HEADER_EVENT_TIME = header.HEADER_EVENT_TIME[0].Value;
                }

                if (header.HEADER_MESSAGE_ID != null && header.HEADER_MESSAGE_ID.Length > 0) {
                    head.HEADER_MESSAGE_ID = header.HEADER_MESSAGE_ID[0].Value;
                }

                if (header.HEADER_SEQUENCE_NUMBER != null && header.HEADER_SEQUENCE_NUMBER.Length > 0) {
                    head.HEADER_SEQUENCE_NUMBER = header.HEADER_SEQUENCE_NUMBER[0].Value;
                }

                if (header.HEADER_MESSAGE_VERSION != null && header.HEADER_MESSAGE_VERSION.Length > 0) {
                    head.HEADER_MESSAGE_VERSION = header.HEADER_MESSAGE_VERSION[0].Value;
                }

                if (header.HEADER_MESSAGE_REVISION != null && header.HEADER_MESSAGE_REVISION.Length > 0) {
                    head.HEADER_MESSAGE_REVISION = header.HEADER_MESSAGE_REVISION[0].Value;
                }

                if (header.HEADER_SOURCE_SYS != null && header.HEADER_SOURCE_SYS.Length > 0) {
                    head.HEADER_SOURCE_SYS = header.HEADER_SOURCE_SYS[0].Value;
                }

                if (header.HEADER_DESTINATION_SYS != null && header.HEADER_DESTINATION_SYS.Length > 0) {
                    head.HEADER_DESTINATION_SYS = header.HEADER_DESTINATION_SYS[0].Value;
                }

                if (header.HEADER_DISTRICT_NAME != null && header.HEADER_DISTRICT_NAME.Length > 0) {
                    head.HEADER_DISTRICT_NAME = header.HEADER_DISTRICT_NAME[0].Value;
                }

                if (header.HEADER_DISTRICT_SCAC != null && header.HEADER_DISTRICT_SCAC.Length > 0) {
                    head.HEADER_DISTRICT_SCAC = header.HEADER_DISTRICT_SCAC[0].Value;
                }

                if (header.HEADER_USER_ID != null && header.HEADER_USER_ID.Length > 0) {
                    head.HEADER_USER_ID = header.HEADER_USER_ID[0].Value;
                }

                dc_mess_2.HEADER = head;

            }

            if (content != null) {
                PTC_DC_MESSCONTENT_2 cont = new PTC_DC_MESSCONTENT_2();
                if (content.BULLETIN_ITEM_NUMBER != null && content.BULLETIN_ITEM_NUMBER.Length > 0) {
                    cont.BULLETIN_ITEM_NUMBER = content.BULLETIN_ITEM_NUMBER[0].Value;
                }

                if (content.BULLETIN_ITEM_TYPE != null && content.BULLETIN_ITEM_TYPE.Length > 0) {
                    cont.BULLETIN_ITEM_TYPE = content.BULLETIN_ITEM_TYPE[0].Value;
                }

                if (content.LIMIT != null && content.LIMIT.Length > 0) {
                    cont.LIMIT = content.LIMIT[0].Value;
                }

                if (content.EYE_CATCHER_TEXT != null && content.EYE_CATCHER_TEXT.Length > 0) {
                    cont.EYE_CATCHER_TEXT = content.EYE_CATCHER_TEXT[0].Value;
                }

                if (content.EFFECTIVE_DATE != null && content.EFFECTIVE_DATE.Length > 0) {
                    cont.EFFECTIVE_DATE = content.EFFECTIVE_DATE[0].Value;
                }

                if (content.EFFECTIVE_TIME != null && content.EFFECTIVE_TIME.Length > 0) {
                    cont.EFFECTIVE_TIME = content.EFFECTIVE_TIME[0].Value;
                }

                if (content.EXPIRATION_DATE != null && content.EXPIRATION_DATE.Length > 0) {
                    cont.EXPIRATION_DATE = content.EXPIRATION_DATE[0].Value;
                }

                if (content.EXPIRATION_TIME != null && content.EXPIRATION_TIME.Length > 0) {
                    cont.EXPIRATION_TIME = content.EXPIRATION_TIME[0].Value;
                }

                if (content.LINE_COUNT != null && content.LINE_COUNT.Length > 0) {
                    cont.LINE_COUNT = content.LINE_COUNT[0].Value;
                }

                if (content.TEXT_RECORD != null && content.TEXT_RECORD.Length > 0) {
                    for (int i = 0; i < content.TEXT_RECORD.Length; i++) {
                        PTC_DC_MESSTEXT_RECORD_2 text_record = new PTC_DC_MESSTEXT_RECORD_2();
                        if (content.TEXT_RECORD[i].TEXT_SEQUENCE != null && content.TEXT_RECORD[i].TEXT_SEQUENCE.Length > 0) {
                            text_record.TEXT_SEQUENCE = content.TEXT_RECORD[i].TEXT_SEQUENCE[0].Value;
                        }

                        if (content.TEXT_RECORD[i].TEXT != null && content.TEXT_RECORD[i].TEXT.Length > 0) {
                            text_record.TEXT = content.TEXT_RECORD[i].TEXT[0].Value;
                        }

                        cont.addTEXT_RECORD(text_record);
                    }

                }

                if (content.SCAC != null && content.SCAC.Length > 0) {
                    cont.SCAC = content.SCAC[0].Value;
                }

                if (content.SYMBOL != null && content.SYMBOL.Length > 0) {
                    cont.SYMBOL = content.SYMBOL[0].Value;
                }

                if (content.SECTION != null && content.SECTION.Length > 0) {
                    cont.SECTION = content.SECTION[0].Value;
                }

                if (content.ORIGIN_DATE != null && content.ORIGIN_DATE.Length > 0) {
                    cont.ORIGIN_DATE = content.ORIGIN_DATE[0].Value;
                }

                if (content.CREW_ACK_REQUIRED != null && content.CREW_ACK_REQUIRED.Length > 0) {
                    cont.CREW_ACK_REQUIRED = content.CREW_ACK_REQUIRED[0].Value;
                }

                if (content.ELECTRONIC_ACK_REQUESTED != null && content.ELECTRONIC_ACK_REQUESTED.Length > 0) {
                    cont.ELECTRONIC_ACK_REQUESTED = content.ELECTRONIC_ACK_REQUESTED[0].Value;
                }

                dc_mess_2.CONTENT = cont;

            }

            return dc_mess_2;
        }
    }

    public partial class PTC_DC_MESSHEADER_2 {
        private string thisHEADER_EVENT_DATE = "";
        private string thisHEADER_EVENT_TIME = "";
        private string thisHEADER_MESSAGE_ID = "";
        private string thisHEADER_SEQUENCE_NUMBER = "";
        private string thisHEADER_MESSAGE_VERSION = "";
        private string thisHEADER_MESSAGE_REVISION = "";
        private string thisHEADER_SOURCE_SYS = "";
        private string thisHEADER_DESTINATION_SYS = "";
        private string thisHEADER_DISTRICT_NAME = "";
        private string thisHEADER_DISTRICT_SCAC = "";
        private string thisHEADER_USER_ID = "";

        public string HEADER_EVENT_DATE {
            get { return this.thisHEADER_EVENT_DATE; }
            set { this.thisHEADER_EVENT_DATE = value; }
        }

        public string HEADER_EVENT_TIME {
            get { return this.thisHEADER_EVENT_TIME; }
            set { this.thisHEADER_EVENT_TIME = value; }
        }

        public string HEADER_MESSAGE_ID {
            get { return this.thisHEADER_MESSAGE_ID; }
            set { this.thisHEADER_MESSAGE_ID = value; }
        }

        public string HEADER_SEQUENCE_NUMBER {
            get { return this.thisHEADER_SEQUENCE_NUMBER; }
            set { this.thisHEADER_SEQUENCE_NUMBER = value; }
        }

        public string HEADER_MESSAGE_VERSION {
            get { return this.thisHEADER_MESSAGE_VERSION; }
            set { this.thisHEADER_MESSAGE_VERSION = value; }
        }

        public string HEADER_MESSAGE_REVISION {
            get { return this.thisHEADER_MESSAGE_REVISION; }
            set { this.thisHEADER_MESSAGE_REVISION = value; }
        }

        public string HEADER_SOURCE_SYS {
            get { return this.thisHEADER_SOURCE_SYS; }
            set { this.thisHEADER_SOURCE_SYS = value; }
        }

        public string HEADER_DESTINATION_SYS {
            get { return this.thisHEADER_DESTINATION_SYS; }
            set { this.thisHEADER_DESTINATION_SYS = value; }
        }

        public string HEADER_DISTRICT_NAME {
            get { return this.thisHEADER_DISTRICT_NAME; }
            set { this.thisHEADER_DISTRICT_NAME = value; }
        }

        public string HEADER_DISTRICT_SCAC {
            get { return this.thisHEADER_DISTRICT_SCAC; }
            set { this.thisHEADER_DISTRICT_SCAC = value; }
        }

        public string HEADER_USER_ID {
            get { return this.thisHEADER_USER_ID; }
            set { this.thisHEADER_USER_ID = value; }
        }

    }

    public partial class PTC_DC_MESSCONTENT_2 {
        private string thisBULLETIN_ITEM_NUMBER = "";
        private string thisBULLETIN_ITEM_TYPE = "";
        private string thisLIMIT = "";
        private string thisEYE_CATCHER_TEXT = "";
        private string thisEFFECTIVE_DATE = "";
        private string thisEFFECTIVE_TIME = "";
        private string thisEXPIRATION_DATE = "";
        private string thisEXPIRATION_TIME = "";
        private string thisLINE_COUNT = "";
        private ArrayList thisTEXT_RECORD = new ArrayList();
        private string thisSCAC = "";
        private string thisSYMBOL = "";
        private string thisSECTION = "";
        private string thisORIGIN_DATE = "";
        private string thisCREW_ACK_REQUIRED = "";
        private string thisELECTRONIC_ACK_REQUESTED = "";

        public string BULLETIN_ITEM_NUMBER {
            get { return this.thisBULLETIN_ITEM_NUMBER; }
            set { this.thisBULLETIN_ITEM_NUMBER = value; }
        }

        public string BULLETIN_ITEM_TYPE {
            get { return this.thisBULLETIN_ITEM_TYPE; }
            set { this.thisBULLETIN_ITEM_TYPE = value; }
        }

        public string LIMIT {
            get { return this.thisLIMIT; }
            set { this.thisLIMIT = value; }
        }

        public string EYE_CATCHER_TEXT {
            get { return this.thisEYE_CATCHER_TEXT; }
            set { this.thisEYE_CATCHER_TEXT = value; }
        }

        public string EFFECTIVE_DATE {
            get { return this.thisEFFECTIVE_DATE; }
            set { this.thisEFFECTIVE_DATE = value; }
        }

        public string EFFECTIVE_TIME {
            get { return this.thisEFFECTIVE_TIME; }
            set { this.thisEFFECTIVE_TIME = value; }
        }

        public string EXPIRATION_DATE {
            get { return this.thisEXPIRATION_DATE; }
            set { this.thisEXPIRATION_DATE = value; }
        }

        public string EXPIRATION_TIME {
            get { return this.thisEXPIRATION_TIME; }
            set { this.thisEXPIRATION_TIME = value; }
        }

        public string LINE_COUNT {
            get { return this.thisLINE_COUNT; }
            set { this.thisLINE_COUNT = value; }
        }

        public ArrayList TEXT_RECORD {
            get { return this.thisTEXT_RECORD; }
            set { this.thisTEXT_RECORD = value; }
        }

        public void addTEXT_RECORD(PTC_DC_MESSTEXT_RECORD_2 text_record) {
            this.TEXT_RECORD.Add(text_record);
            this.LINE_COUNT = this.TEXT_RECORD.Count.ToString();
        }

        public void removeTEXT_RECORD(int index) {
            this.TEXT_RECORD.RemoveAt(index);
            this.LINE_COUNT = this.TEXT_RECORD.Count.ToString();
        }

        public string SCAC {
            get { return this.thisSCAC; }
            set { this.thisSCAC = value; }
        }

        public string SYMBOL {
            get { return this.thisSYMBOL; }
            set { this.thisSYMBOL = value; }
        }

        public string SECTION {
            get { return this.thisSECTION; }
            set { this.thisSECTION = value; }
        }

        public string ORIGIN_DATE {
            get { return this.thisORIGIN_DATE; }
            set { this.thisORIGIN_DATE = value; }
        }

        public string CREW_ACK_REQUIRED {
            get { return this.thisCREW_ACK_REQUIRED; }
            set { this.thisCREW_ACK_REQUIRED = value; }
        }

        public string ELECTRONIC_ACK_REQUESTED {
            get { return this.thisELECTRONIC_ACK_REQUESTED; }
            set { this.thisELECTRONIC_ACK_REQUESTED = value; }
        }

    }

    public partial class PTC_DC_MESSTEXT_RECORD_2 {
        private string thisTEXT_SEQUENCE = "";
        private string thisTEXT = "";

        public string TEXT_SEQUENCE {
            get { return this.thisTEXT_SEQUENCE; }
            set { this.thisTEXT_SEQUENCE = value; }
        }

        public string TEXT {
            get { return this.thisTEXT; }
            set { this.thisTEXT = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class DC_MESS_2 {
        private object[] itemsField;

        [System.Xml.Serialization.XmlElementAttribute("HEADER", typeof(DC_MESSHEADER_2), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]

        [System.Xml.Serialization.XmlElementAttribute("CONTENT", typeof(DC_MESSCONTENT_2), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]


        public object[] Items {
            get {
                return this.itemsField;
            }
    	    set {
    	        this.itemsField = value;
    	    }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DC_MESSHEADER_2 {
        private DC_MESSHEADERHEADER_EVENT_DATE_2[] HEADER_EVENT_DATEField;
        private DC_MESSHEADERHEADER_EVENT_TIME_2[] HEADER_EVENT_TIMEField;
        private DC_MESSHEADERHEADER_MESSAGE_ID_2[] HEADER_MESSAGE_IDField;
        private DC_MESSHEADERHEADER_SEQUENCE_NUMBER_2[] HEADER_SEQUENCE_NUMBERField;
        private DC_MESSHEADERHEADER_MESSAGE_VERSION_2[] HEADER_MESSAGE_VERSIONField;
        private DC_MESSHEADERHEADER_MESSAGE_REVISION_2[] HEADER_MESSAGE_REVISIONField;
        private DC_MESSHEADERHEADER_SOURCE_SYS_2[] HEADER_SOURCE_SYSField;
        private DC_MESSHEADERHEADER_DESTINATION_SYS_2[] HEADER_DESTINATION_SYSField;
        private DC_MESSHEADERHEADER_DISTRICT_NAME_2[] HEADER_DISTRICT_NAMEField;
        private DC_MESSHEADERHEADER_DISTRICT_SCAC_2[] HEADER_DISTRICT_SCACField;
        private DC_MESSHEADERHEADER_USER_ID_2[] HEADER_USER_IDField;

        [System.Xml.Serialization.XmlElementAttribute("HEADER_EVENT_DATE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DC_MESSHEADERHEADER_EVENT_DATE_2[] HEADER_EVENT_DATE {
            get { return this.HEADER_EVENT_DATEField; }
            set { this.HEADER_EVENT_DATEField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("HEADER_EVENT_TIME", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DC_MESSHEADERHEADER_EVENT_TIME_2[] HEADER_EVENT_TIME {
            get { return this.HEADER_EVENT_TIMEField; }
            set { this.HEADER_EVENT_TIMEField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("HEADER_MESSAGE_ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DC_MESSHEADERHEADER_MESSAGE_ID_2[] HEADER_MESSAGE_ID {
            get { return this.HEADER_MESSAGE_IDField; }
            set { this.HEADER_MESSAGE_IDField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("HEADER_SEQUENCE_NUMBER", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DC_MESSHEADERHEADER_SEQUENCE_NUMBER_2[] HEADER_SEQUENCE_NUMBER {
            get { return this.HEADER_SEQUENCE_NUMBERField; }
            set { this.HEADER_SEQUENCE_NUMBERField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("HEADER_MESSAGE_VERSION", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DC_MESSHEADERHEADER_MESSAGE_VERSION_2[] HEADER_MESSAGE_VERSION {
            get { return this.HEADER_MESSAGE_VERSIONField; }
            set { this.HEADER_MESSAGE_VERSIONField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("HEADER_MESSAGE_REVISION", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DC_MESSHEADERHEADER_MESSAGE_REVISION_2[] HEADER_MESSAGE_REVISION {
            get { return this.HEADER_MESSAGE_REVISIONField; }
            set { this.HEADER_MESSAGE_REVISIONField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("HEADER_SOURCE_SYS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DC_MESSHEADERHEADER_SOURCE_SYS_2[] HEADER_SOURCE_SYS {
            get { return this.HEADER_SOURCE_SYSField; }
            set { this.HEADER_SOURCE_SYSField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("HEADER_DESTINATION_SYS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DC_MESSHEADERHEADER_DESTINATION_SYS_2[] HEADER_DESTINATION_SYS {
            get { return this.HEADER_DESTINATION_SYSField; }
            set { this.HEADER_DESTINATION_SYSField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("HEADER_DISTRICT_NAME", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DC_MESSHEADERHEADER_DISTRICT_NAME_2[] HEADER_DISTRICT_NAME {
            get { return this.HEADER_DISTRICT_NAMEField; }
            set { this.HEADER_DISTRICT_NAMEField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("HEADER_DISTRICT_SCAC", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DC_MESSHEADERHEADER_DISTRICT_SCAC_2[] HEADER_DISTRICT_SCAC {
            get { return this.HEADER_DISTRICT_SCACField; }
            set { this.HEADER_DISTRICT_SCACField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("HEADER_USER_ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DC_MESSHEADERHEADER_USER_ID_2[] HEADER_USER_ID {
            get { return this.HEADER_USER_IDField; }
            set { this.HEADER_USER_IDField = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DC_MESSHEADERHEADER_EVENT_DATE_2 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DC_MESSHEADERHEADER_EVENT_TIME_2 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DC_MESSHEADERHEADER_MESSAGE_ID_2 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DC_MESSHEADERHEADER_SEQUENCE_NUMBER_2 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DC_MESSHEADERHEADER_MESSAGE_VERSION_2 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DC_MESSHEADERHEADER_MESSAGE_REVISION_2 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DC_MESSHEADERHEADER_SOURCE_SYS_2 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DC_MESSHEADERHEADER_DESTINATION_SYS_2 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DC_MESSHEADERHEADER_DISTRICT_NAME_2 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DC_MESSHEADERHEADER_DISTRICT_SCAC_2 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DC_MESSHEADERHEADER_USER_ID_2 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DC_MESSCONTENT_2 {
        private DC_MESSCONTENTBULLETIN_ITEM_NUMBER_2[] BULLETIN_ITEM_NUMBERField;
        private DC_MESSCONTENTBULLETIN_ITEM_TYPE_2[] BULLETIN_ITEM_TYPEField;
        private DC_MESSCONTENTLIMIT_2[] LIMITField;
        private DC_MESSCONTENTEYE_CATCHER_TEXT_2[] EYE_CATCHER_TEXTField;
        private DC_MESSCONTENTEFFECTIVE_DATE_2[] EFFECTIVE_DATEField;
        private DC_MESSCONTENTEFFECTIVE_TIME_2[] EFFECTIVE_TIMEField;
        private DC_MESSCONTENTEXPIRATION_DATE_2[] EXPIRATION_DATEField;
        private DC_MESSCONTENTEXPIRATION_TIME_2[] EXPIRATION_TIMEField;
        private DC_MESSCONTENTLINE_COUNT_2[] LINE_COUNTField;
        private DC_MESSCONTENTTEXT_RECORD_2[] TEXT_RECORDField;
        private DC_MESSCONTENTSCAC_2[] SCACField;
        private DC_MESSCONTENTSYMBOL_2[] SYMBOLField;
        private DC_MESSCONTENTSECTION_2[] SECTIONField;
        private DC_MESSCONTENTORIGIN_DATE_2[] ORIGIN_DATEField;
        private DC_MESSCONTENTCREW_ACK_REQUIRED_2[] CREW_ACK_REQUIREDField;
        private DC_MESSCONTENTELECTRONIC_ACK_REQUESTED_2[] ELECTRONIC_ACK_REQUESTEDField;

        [System.Xml.Serialization.XmlElementAttribute("BULLETIN_ITEM_NUMBER", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DC_MESSCONTENTBULLETIN_ITEM_NUMBER_2[] BULLETIN_ITEM_NUMBER {
            get { return this.BULLETIN_ITEM_NUMBERField; }
            set { this.BULLETIN_ITEM_NUMBERField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("BULLETIN_ITEM_TYPE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DC_MESSCONTENTBULLETIN_ITEM_TYPE_2[] BULLETIN_ITEM_TYPE {
            get { return this.BULLETIN_ITEM_TYPEField; }
            set { this.BULLETIN_ITEM_TYPEField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("LIMIT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DC_MESSCONTENTLIMIT_2[] LIMIT {
            get { return this.LIMITField; }
            set { this.LIMITField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("EYE_CATCHER_TEXT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DC_MESSCONTENTEYE_CATCHER_TEXT_2[] EYE_CATCHER_TEXT {
            get { return this.EYE_CATCHER_TEXTField; }
            set { this.EYE_CATCHER_TEXTField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("EFFECTIVE_DATE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DC_MESSCONTENTEFFECTIVE_DATE_2[] EFFECTIVE_DATE {
            get { return this.EFFECTIVE_DATEField; }
            set { this.EFFECTIVE_DATEField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("EFFECTIVE_TIME", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DC_MESSCONTENTEFFECTIVE_TIME_2[] EFFECTIVE_TIME {
            get { return this.EFFECTIVE_TIMEField; }
            set { this.EFFECTIVE_TIMEField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("EXPIRATION_DATE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DC_MESSCONTENTEXPIRATION_DATE_2[] EXPIRATION_DATE {
            get { return this.EXPIRATION_DATEField; }
            set { this.EXPIRATION_DATEField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("EXPIRATION_TIME", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DC_MESSCONTENTEXPIRATION_TIME_2[] EXPIRATION_TIME {
            get { return this.EXPIRATION_TIMEField; }
            set { this.EXPIRATION_TIMEField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("LINE_COUNT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DC_MESSCONTENTLINE_COUNT_2[] LINE_COUNT {
            get { return this.LINE_COUNTField; }
            set { this.LINE_COUNTField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("TEXT_RECORD", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DC_MESSCONTENTTEXT_RECORD_2[] TEXT_RECORD {
            get { return this.TEXT_RECORDField; }
            set { this.TEXT_RECORDField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("SCAC", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DC_MESSCONTENTSCAC_2[] SCAC {
            get { return this.SCACField; }
            set { this.SCACField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("SYMBOL", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DC_MESSCONTENTSYMBOL_2[] SYMBOL {
            get { return this.SYMBOLField; }
            set { this.SYMBOLField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("SECTION", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DC_MESSCONTENTSECTION_2[] SECTION {
            get { return this.SECTIONField; }
            set { this.SECTIONField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("ORIGIN_DATE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DC_MESSCONTENTORIGIN_DATE_2[] ORIGIN_DATE {
            get { return this.ORIGIN_DATEField; }
            set { this.ORIGIN_DATEField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("CREW_ACK_REQUIRED", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DC_MESSCONTENTCREW_ACK_REQUIRED_2[] CREW_ACK_REQUIRED {
            get { return this.CREW_ACK_REQUIREDField; }
            set { this.CREW_ACK_REQUIREDField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("ELECTRONIC_ACK_REQUESTED", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DC_MESSCONTENTELECTRONIC_ACK_REQUESTED_2[] ELECTRONIC_ACK_REQUESTED {
            get { return this.ELECTRONIC_ACK_REQUESTEDField; }
            set { this.ELECTRONIC_ACK_REQUESTEDField = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DC_MESSCONTENTBULLETIN_ITEM_NUMBER_2 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DC_MESSCONTENTBULLETIN_ITEM_TYPE_2 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DC_MESSCONTENTLIMIT_2 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DC_MESSCONTENTEYE_CATCHER_TEXT_2 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DC_MESSCONTENTEFFECTIVE_DATE_2 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DC_MESSCONTENTEFFECTIVE_TIME_2 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DC_MESSCONTENTEXPIRATION_DATE_2 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DC_MESSCONTENTEXPIRATION_TIME_2 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DC_MESSCONTENTLINE_COUNT_2 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DC_MESSCONTENTSCAC_2 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DC_MESSCONTENTSYMBOL_2 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DC_MESSCONTENTSECTION_2 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DC_MESSCONTENTORIGIN_DATE_2 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DC_MESSCONTENTCREW_ACK_REQUIRED_2 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DC_MESSCONTENTELECTRONIC_ACK_REQUESTED_2 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DC_MESSCONTENTTEXT_RECORD_2 {
        private DC_MESSTEXT_RECORDTEXT_SEQUENCE_2[] TEXT_SEQUENCEField;
        private DC_MESSTEXT_RECORDTEXT_2[] TEXTField;

        [System.Xml.Serialization.XmlElementAttribute("TEXT_SEQUENCE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DC_MESSTEXT_RECORDTEXT_SEQUENCE_2[] TEXT_SEQUENCE {
            get { return this.TEXT_SEQUENCEField; }
            set { this.TEXT_SEQUENCEField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("TEXT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DC_MESSTEXT_RECORDTEXT_2[] TEXT {
            get { return this.TEXTField; }
            set { this.TEXTField = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DC_MESSTEXT_RECORDTEXT_SEQUENCE_2 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DC_MESSTEXT_RECORDTEXT_2 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

}
