//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a buildPTCMessages.py.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.IO;
using System.Xml;
using System.Xml.Serialization;
using System.Collections;
using STE.Code_Utils.messages;

namespace STE.Code_Utils.messages.PTC
{
    public partial class PTC_DG_BULI_3 {
        private PTC_DG_BULIHEADER_3 thisHEADER;
        private PTC_DG_BULICONTENT_3 thisCONTENT;

        public PTC_DG_BULIHEADER_3 HEADER {
            get { return this.thisHEADER; }
            set { this.thisHEADER = value; }
        }

        public PTC_DG_BULICONTENT_3 CONTENT {
            get { return this.thisCONTENT; }
            set { this.thisCONTENT = value; }
        }

        public static PTC_DG_BULI_3 fromSerializableObject(DG_BULI_3 message) {
            PTC_DG_BULI_3 dg_buli_3 = new PTC_DG_BULI_3();
            DG_BULIHEADER_3 header = null;
            DG_BULICONTENT_3 content = null;
            if (message.Items.Length == 1) {
                content = (DG_BULICONTENT_3) message.Items[0];
            }
            else {
                header = (DG_BULIHEADER_3) message.Items[0];
                content = (DG_BULICONTENT_3) message.Items[1];
            }

            if (header != null) {
                PTC_DG_BULIHEADER_3 head = new PTC_DG_BULIHEADER_3();
                if (header.HEADER_EVENT_DATE != null && header.HEADER_EVENT_DATE.Length > 0) {
                    head.HEADER_EVENT_DATE = header.HEADER_EVENT_DATE[0].Value;
                }

                if (header.HEADER_EVENT_TIME != null && header.HEADER_EVENT_TIME.Length > 0) {
                    head.HEADER_EVENT_TIME = header.HEADER_EVENT_TIME[0].Value;
                }

                if (header.HEADER_MESSAGE_ID != null && header.HEADER_MESSAGE_ID.Length > 0) {
                    head.HEADER_MESSAGE_ID = header.HEADER_MESSAGE_ID[0].Value;
                }

                if (header.HEADER_SEQUENCE_NUMBER != null && header.HEADER_SEQUENCE_NUMBER.Length > 0) {
                    head.HEADER_SEQUENCE_NUMBER = header.HEADER_SEQUENCE_NUMBER[0].Value;
                }

                if (header.HEADER_MESSAGE_VERSION != null && header.HEADER_MESSAGE_VERSION.Length > 0) {
                    head.HEADER_MESSAGE_VERSION = header.HEADER_MESSAGE_VERSION[0].Value;
                }

                if (header.HEADER_MESSAGE_REVISION != null && header.HEADER_MESSAGE_REVISION.Length > 0) {
                    head.HEADER_MESSAGE_REVISION = header.HEADER_MESSAGE_REVISION[0].Value;
                }

                if (header.HEADER_SOURCE_SYS != null && header.HEADER_SOURCE_SYS.Length > 0) {
                    head.HEADER_SOURCE_SYS = header.HEADER_SOURCE_SYS[0].Value;
                }

                if (header.HEADER_DESTINATION_SYS != null && header.HEADER_DESTINATION_SYS.Length > 0) {
                    head.HEADER_DESTINATION_SYS = header.HEADER_DESTINATION_SYS[0].Value;
                }

                if (header.HEADER_DISTRICT_NAME != null && header.HEADER_DISTRICT_NAME.Length > 0) {
                    head.HEADER_DISTRICT_NAME = header.HEADER_DISTRICT_NAME[0].Value;
                }

                if (header.HEADER_DISTRICT_SCAC != null && header.HEADER_DISTRICT_SCAC.Length > 0) {
                    head.HEADER_DISTRICT_SCAC = header.HEADER_DISTRICT_SCAC[0].Value;
                }

                if (header.HEADER_USER_ID != null && header.HEADER_USER_ID.Length > 0) {
                    head.HEADER_USER_ID = header.HEADER_USER_ID[0].Value;
                }

                dg_buli_3.HEADER = head;

            }

            if (content != null) {
                PTC_DG_BULICONTENT_3 cont = new PTC_DG_BULICONTENT_3();
                if (content.BULLETIN_ITEM_NUMBER != null && content.BULLETIN_ITEM_NUMBER.Length > 0) {
                    cont.BULLETIN_ITEM_NUMBER = content.BULLETIN_ITEM_NUMBER[0].Value;
                }

                if (content.BULLETIN_ITEM_TYPE != null && content.BULLETIN_ITEM_TYPE.Length > 0) {
                    cont.BULLETIN_ITEM_TYPE = content.BULLETIN_ITEM_TYPE[0].Value;
                }

                if (content.FROM_LIMIT != null && content.FROM_LIMIT.Length > 0) {
                    cont.FROM_LIMIT = content.FROM_LIMIT[0].Value;
                }

                if (content.TO_LIMIT != null && content.TO_LIMIT.Length > 0) {
                    cont.TO_LIMIT = content.TO_LIMIT[0].Value;
                }

                if (content.EYE_CATCHER_TEXT != null && content.EYE_CATCHER_TEXT.Length > 0) {
                    cont.EYE_CATCHER_TEXT = content.EYE_CATCHER_TEXT[0].Value;
                }

                if (content.EFFECTIVE_DATE != null && content.EFFECTIVE_DATE.Length > 0) {
                    cont.EFFECTIVE_DATE = content.EFFECTIVE_DATE[0].Value;
                }

                if (content.EFFECTIVE_TIME != null && content.EFFECTIVE_TIME.Length > 0) {
                    cont.EFFECTIVE_TIME = content.EFFECTIVE_TIME[0].Value;
                }

                if (content.EXPIRATION_DATE != null && content.EXPIRATION_DATE.Length > 0) {
                    cont.EXPIRATION_DATE = content.EXPIRATION_DATE[0].Value;
                }

                if (content.EXPIRATION_TIME != null && content.EXPIRATION_TIME.Length > 0) {
                    cont.EXPIRATION_TIME = content.EXPIRATION_TIME[0].Value;
                }

                if (content.SPEED != null && content.SPEED.Length > 0) {
                    cont.SPEED = content.SPEED[0].Value;
                }

                if (content.HEO_SPEED_RESTRICTION != null && content.HEO_SPEED_RESTRICTION.Length > 0) {
                    cont.HEO_SPEED_RESTRICTION = content.HEO_SPEED_RESTRICTION[0].Value;
                }

                if (content.CONTACT != null && content.CONTACT.Length > 0) {
                    cont.CONTACT = content.CONTACT[0].Value;
                }

                if (content.TOD_FILTER_COUNT != null && content.TOD_FILTER_COUNT.Length > 0) {
                    cont.TOD_FILTER_COUNT = content.TOD_FILTER_COUNT[0].Value;
                }

                if (content.TOD_RECORD != null && content.TOD_RECORD.Length > 0) {
                    for (int i = 0; i < content.TOD_RECORD.Length; i++) {
                        PTC_DG_BULITOD_RECORD_3 tod_record = new PTC_DG_BULITOD_RECORD_3();
                        if (content.TOD_RECORD[i].TOD_DAY_OF_WEEK != null && content.TOD_RECORD[i].TOD_DAY_OF_WEEK.Length > 0) {
                            tod_record.TOD_DAY_OF_WEEK = content.TOD_RECORD[i].TOD_DAY_OF_WEEK[0].Value;
                        }

                        if (content.TOD_RECORD[i].TOD_START_TIME != null && content.TOD_RECORD[i].TOD_START_TIME.Length > 0) {
                            tod_record.TOD_START_TIME = content.TOD_RECORD[i].TOD_START_TIME[0].Value;
                        }

                        if (content.TOD_RECORD[i].TOD_END_TIME != null && content.TOD_RECORD[i].TOD_END_TIME.Length > 0) {
                            tod_record.TOD_END_TIME = content.TOD_RECORD[i].TOD_END_TIME[0].Value;
                        }

                        cont.addTOD_RECORD(tod_record);
                    }

                }

                if (content.ROUTE_COUNT != null && content.ROUTE_COUNT.Length > 0) {
                    cont.ROUTE_COUNT = content.ROUTE_COUNT[0].Value;
                }

                if (content.ROUTE_RECORD != null && content.ROUTE_RECORD.Length > 0) {
                    for (int i = 0; i < content.ROUTE_RECORD.Length; i++) {
                        PTC_DG_BULIROUTE_RECORD_3 route_record = new PTC_DG_BULIROUTE_RECORD_3();
                        if (content.ROUTE_RECORD[i].TRACK != null && content.ROUTE_RECORD[i].TRACK.Length > 0) {
                            route_record.TRACK = content.ROUTE_RECORD[i].TRACK[0].Value;
                        }

                        if (content.ROUTE_RECORD[i].START_DISTRICT != null && content.ROUTE_RECORD[i].START_DISTRICT.Length > 0) {
                            route_record.START_DISTRICT = content.ROUTE_RECORD[i].START_DISTRICT[0].Value;
                        }

                        if (content.ROUTE_RECORD[i].START_MILEPOST != null && content.ROUTE_RECORD[i].START_MILEPOST.Length > 0) {
                            route_record.START_MILEPOST = content.ROUTE_RECORD[i].START_MILEPOST[0].Value;
                        }

                        if (content.ROUTE_RECORD[i].END_DISTRICT != null && content.ROUTE_RECORD[i].END_DISTRICT.Length > 0) {
                            route_record.END_DISTRICT = content.ROUTE_RECORD[i].END_DISTRICT[0].Value;
                        }

                        if (content.ROUTE_RECORD[i].END_MILEPOST != null && content.ROUTE_RECORD[i].END_MILEPOST.Length > 0) {
                            route_record.END_MILEPOST = content.ROUTE_RECORD[i].END_MILEPOST[0].Value;
                        }

                        cont.addROUTE_RECORD(route_record);
                    }

                }

                if (content.ROUTE_DISTRICT_COUNT != null && content.ROUTE_DISTRICT_COUNT.Length > 0) {
                    cont.ROUTE_DISTRICT_COUNT = content.ROUTE_DISTRICT_COUNT[0].Value;
                }

                if (content.ROUTE_DISTRICT_RECORD != null && content.ROUTE_DISTRICT_RECORD.Length > 0) {
                    for (int i = 0; i < content.ROUTE_DISTRICT_RECORD.Length; i++) {
                        PTC_DG_BULIROUTE_DISTRICT_RECORD_3 route_district_record = new PTC_DG_BULIROUTE_DISTRICT_RECORD_3();
                        if (content.ROUTE_DISTRICT_RECORD[i].ROUTE_DISTRICT_NAME != null && content.ROUTE_DISTRICT_RECORD[i].ROUTE_DISTRICT_NAME.Length > 0) {
                            route_district_record.ROUTE_DISTRICT_NAME = content.ROUTE_DISTRICT_RECORD[i].ROUTE_DISTRICT_NAME[0].Value;
                        }

                        cont.addROUTE_DISTRICT_RECORD(route_district_record);
                    }

                }

                if (content.CROSSING_ID != null && content.CROSSING_ID.Length > 0) {
                    cont.CROSSING_ID = content.CROSSING_ID[0].Value;
                }

                if (content.CROSSING_DISTRICT_COUNT != null && content.CROSSING_DISTRICT_COUNT.Length > 0) {
                    cont.CROSSING_DISTRICT_COUNT = content.CROSSING_DISTRICT_COUNT[0].Value;
                }

                if (content.CROSSING_RECORD != null && content.CROSSING_RECORD.Length > 0) {
                    for (int i = 0; i < content.CROSSING_RECORD.Length; i++) {
                        PTC_DG_BULICROSSING_RECORD_3 crossing_record = new PTC_DG_BULICROSSING_RECORD_3();
                        if (content.CROSSING_RECORD[i].CROSSING_DISTRICT_NAME != null && content.CROSSING_RECORD[i].CROSSING_DISTRICT_NAME.Length > 0) {
                            crossing_record.CROSSING_DISTRICT_NAME = content.CROSSING_RECORD[i].CROSSING_DISTRICT_NAME[0].Value;
                        }

                        cont.addCROSSING_RECORD(crossing_record);
                    }

                }

                if (content.LINE_COUNT != null && content.LINE_COUNT.Length > 0) {
                    cont.LINE_COUNT = content.LINE_COUNT[0].Value;
                }

                if (content.TEXT_RECORD != null && content.TEXT_RECORD.Length > 0) {
                    for (int i = 0; i < content.TEXT_RECORD.Length; i++) {
                        PTC_DG_BULITEXT_RECORD_3 text_record = new PTC_DG_BULITEXT_RECORD_3();
                        if (content.TEXT_RECORD[i].TEXT_SEQUENCE != null && content.TEXT_RECORD[i].TEXT_SEQUENCE.Length > 0) {
                            text_record.TEXT_SEQUENCE = content.TEXT_RECORD[i].TEXT_SEQUENCE[0].Value;
                        }

                        if (content.TEXT_RECORD[i].TEXT != null && content.TEXT_RECORD[i].TEXT.Length > 0) {
                            text_record.TEXT = content.TEXT_RECORD[i].TEXT[0].Value;
                        }

                        cont.addTEXT_RECORD(text_record);
                    }

                }

                dg_buli_3.CONTENT = cont;

            }

            return dg_buli_3;
        }
    }

    public partial class PTC_DG_BULIHEADER_3 {
        private string thisHEADER_EVENT_DATE = "";
        private string thisHEADER_EVENT_TIME = "";
        private string thisHEADER_MESSAGE_ID = "";
        private string thisHEADER_SEQUENCE_NUMBER = "";
        private string thisHEADER_MESSAGE_VERSION = "";
        private string thisHEADER_MESSAGE_REVISION = "";
        private string thisHEADER_SOURCE_SYS = "";
        private string thisHEADER_DESTINATION_SYS = "";
        private string thisHEADER_DISTRICT_NAME = "";
        private string thisHEADER_DISTRICT_SCAC = "";
        private string thisHEADER_USER_ID = "";

        public string HEADER_EVENT_DATE {
            get { return this.thisHEADER_EVENT_DATE; }
            set { this.thisHEADER_EVENT_DATE = value; }
        }

        public string HEADER_EVENT_TIME {
            get { return this.thisHEADER_EVENT_TIME; }
            set { this.thisHEADER_EVENT_TIME = value; }
        }

        public string HEADER_MESSAGE_ID {
            get { return this.thisHEADER_MESSAGE_ID; }
            set { this.thisHEADER_MESSAGE_ID = value; }
        }

        public string HEADER_SEQUENCE_NUMBER {
            get { return this.thisHEADER_SEQUENCE_NUMBER; }
            set { this.thisHEADER_SEQUENCE_NUMBER = value; }
        }

        public string HEADER_MESSAGE_VERSION {
            get { return this.thisHEADER_MESSAGE_VERSION; }
            set { this.thisHEADER_MESSAGE_VERSION = value; }
        }

        public string HEADER_MESSAGE_REVISION {
            get { return this.thisHEADER_MESSAGE_REVISION; }
            set { this.thisHEADER_MESSAGE_REVISION = value; }
        }

        public string HEADER_SOURCE_SYS {
            get { return this.thisHEADER_SOURCE_SYS; }
            set { this.thisHEADER_SOURCE_SYS = value; }
        }

        public string HEADER_DESTINATION_SYS {
            get { return this.thisHEADER_DESTINATION_SYS; }
            set { this.thisHEADER_DESTINATION_SYS = value; }
        }

        public string HEADER_DISTRICT_NAME {
            get { return this.thisHEADER_DISTRICT_NAME; }
            set { this.thisHEADER_DISTRICT_NAME = value; }
        }

        public string HEADER_DISTRICT_SCAC {
            get { return this.thisHEADER_DISTRICT_SCAC; }
            set { this.thisHEADER_DISTRICT_SCAC = value; }
        }

        public string HEADER_USER_ID {
            get { return this.thisHEADER_USER_ID; }
            set { this.thisHEADER_USER_ID = value; }
        }

    }

    public partial class PTC_DG_BULICONTENT_3 {
        private string thisBULLETIN_ITEM_NUMBER = "";
        private string thisBULLETIN_ITEM_TYPE = "";
        private string thisFROM_LIMIT = "";
        private string thisTO_LIMIT = "";
        private string thisEYE_CATCHER_TEXT = "";
        private string thisEFFECTIVE_DATE = "";
        private string thisEFFECTIVE_TIME = "";
        private string thisEXPIRATION_DATE = "";
        private string thisEXPIRATION_TIME = "";
        private string thisSPEED = "";
        private string thisHEO_SPEED_RESTRICTION = "";
        private string thisCONTACT = "";
        private string thisTOD_FILTER_COUNT = "";
        private ArrayList thisTOD_RECORD = new ArrayList();
        private string thisROUTE_COUNT = "";
        private ArrayList thisROUTE_RECORD = new ArrayList();
        private string thisROUTE_DISTRICT_COUNT = "";
        private ArrayList thisROUTE_DISTRICT_RECORD = new ArrayList();
        private string thisCROSSING_ID = "";
        private string thisCROSSING_DISTRICT_COUNT = "";
        private ArrayList thisCROSSING_RECORD = new ArrayList();
        private string thisLINE_COUNT = "";
        private ArrayList thisTEXT_RECORD = new ArrayList();

        public string BULLETIN_ITEM_NUMBER {
            get { return this.thisBULLETIN_ITEM_NUMBER; }
            set { this.thisBULLETIN_ITEM_NUMBER = value; }
        }

        public string BULLETIN_ITEM_TYPE {
            get { return this.thisBULLETIN_ITEM_TYPE; }
            set { this.thisBULLETIN_ITEM_TYPE = value; }
        }

        public string FROM_LIMIT {
            get { return this.thisFROM_LIMIT; }
            set { this.thisFROM_LIMIT = value; }
        }

        public string TO_LIMIT {
            get { return this.thisTO_LIMIT; }
            set { this.thisTO_LIMIT = value; }
        }

        public string EYE_CATCHER_TEXT {
            get { return this.thisEYE_CATCHER_TEXT; }
            set { this.thisEYE_CATCHER_TEXT = value; }
        }

        public string EFFECTIVE_DATE {
            get { return this.thisEFFECTIVE_DATE; }
            set { this.thisEFFECTIVE_DATE = value; }
        }

        public string EFFECTIVE_TIME {
            get { return this.thisEFFECTIVE_TIME; }
            set { this.thisEFFECTIVE_TIME = value; }
        }

        public string EXPIRATION_DATE {
            get { return this.thisEXPIRATION_DATE; }
            set { this.thisEXPIRATION_DATE = value; }
        }

        public string EXPIRATION_TIME {
            get { return this.thisEXPIRATION_TIME; }
            set { this.thisEXPIRATION_TIME = value; }
        }

        public string SPEED {
            get { return this.thisSPEED; }
            set { this.thisSPEED = value; }
        }

        public string HEO_SPEED_RESTRICTION {
            get { return this.thisHEO_SPEED_RESTRICTION; }
            set { this.thisHEO_SPEED_RESTRICTION = value; }
        }

        public string CONTACT {
            get { return this.thisCONTACT; }
            set { this.thisCONTACT = value; }
        }

        public string TOD_FILTER_COUNT {
            get { return this.thisTOD_FILTER_COUNT; }
            set { this.thisTOD_FILTER_COUNT = value; }
        }

        public ArrayList TOD_RECORD {
            get { return this.thisTOD_RECORD; }
            set { this.thisTOD_RECORD = value; }
        }

        public void addTOD_RECORD(PTC_DG_BULITOD_RECORD_3 tod_record) {
            this.TOD_RECORD.Add(tod_record);
            this.TOD_FILTER_COUNT = this.TOD_RECORD.Count.ToString();
        }

        public void removeTOD_RECORD(int index) {
            this.TOD_RECORD.RemoveAt(index);
            this.TOD_FILTER_COUNT = this.TOD_RECORD.Count.ToString();
        }

        public string ROUTE_COUNT {
            get { return this.thisROUTE_COUNT; }
            set { this.thisROUTE_COUNT = value; }
        }

        public ArrayList ROUTE_RECORD {
            get { return this.thisROUTE_RECORD; }
            set { this.thisROUTE_RECORD = value; }
        }

        public void addROUTE_RECORD(PTC_DG_BULIROUTE_RECORD_3 route_record) {
            this.ROUTE_RECORD.Add(route_record);
            this.ROUTE_COUNT = this.ROUTE_RECORD.Count.ToString();
        }

        public void removeROUTE_RECORD(int index) {
            this.ROUTE_RECORD.RemoveAt(index);
            this.ROUTE_COUNT = this.ROUTE_RECORD.Count.ToString();
        }

        public string ROUTE_DISTRICT_COUNT {
            get { return this.thisROUTE_DISTRICT_COUNT; }
            set { this.thisROUTE_DISTRICT_COUNT = value; }
        }

        public ArrayList ROUTE_DISTRICT_RECORD {
            get { return this.thisROUTE_DISTRICT_RECORD; }
            set { this.thisROUTE_DISTRICT_RECORD = value; }
        }

        public void addROUTE_DISTRICT_RECORD(PTC_DG_BULIROUTE_DISTRICT_RECORD_3 route_district_record) {
            this.ROUTE_DISTRICT_RECORD.Add(route_district_record);
            this.ROUTE_DISTRICT_COUNT = this.ROUTE_DISTRICT_RECORD.Count.ToString();
        }

        public void removeROUTE_DISTRICT_RECORD(int index) {
            this.ROUTE_DISTRICT_RECORD.RemoveAt(index);
            this.ROUTE_DISTRICT_COUNT = this.ROUTE_DISTRICT_RECORD.Count.ToString();
        }

        public string CROSSING_ID {
            get { return this.thisCROSSING_ID; }
            set { this.thisCROSSING_ID = value; }
        }

        public string CROSSING_DISTRICT_COUNT {
            get { return this.thisCROSSING_DISTRICT_COUNT; }
            set { this.thisCROSSING_DISTRICT_COUNT = value; }
        }

        public ArrayList CROSSING_RECORD {
            get { return this.thisCROSSING_RECORD; }
            set { this.thisCROSSING_RECORD = value; }
        }

        public void addCROSSING_RECORD(PTC_DG_BULICROSSING_RECORD_3 crossing_record) {
            this.CROSSING_RECORD.Add(crossing_record);
            this.CROSSING_DISTRICT_COUNT = this.CROSSING_RECORD.Count.ToString();
        }

        public void removeCROSSING_RECORD(int index) {
            this.CROSSING_RECORD.RemoveAt(index);
            this.CROSSING_DISTRICT_COUNT = this.CROSSING_RECORD.Count.ToString();
        }

        public string LINE_COUNT {
            get { return this.thisLINE_COUNT; }
            set { this.thisLINE_COUNT = value; }
        }

        public ArrayList TEXT_RECORD {
            get { return this.thisTEXT_RECORD; }
            set { this.thisTEXT_RECORD = value; }
        }

        public void addTEXT_RECORD(PTC_DG_BULITEXT_RECORD_3 text_record) {
            this.TEXT_RECORD.Add(text_record);
            this.LINE_COUNT = this.TEXT_RECORD.Count.ToString();
        }

        public void removeTEXT_RECORD(int index) {
            this.TEXT_RECORD.RemoveAt(index);
            this.LINE_COUNT = this.TEXT_RECORD.Count.ToString();
        }

    }

    public partial class PTC_DG_BULITOD_RECORD_3 {
        private string thisTOD_DAY_OF_WEEK = "";
        private string thisTOD_START_TIME = "";
        private string thisTOD_END_TIME = "";

        public string TOD_DAY_OF_WEEK {
            get { return this.thisTOD_DAY_OF_WEEK; }
            set { this.thisTOD_DAY_OF_WEEK = value; }
        }

        public string TOD_START_TIME {
            get { return this.thisTOD_START_TIME; }
            set { this.thisTOD_START_TIME = value; }
        }

        public string TOD_END_TIME {
            get { return this.thisTOD_END_TIME; }
            set { this.thisTOD_END_TIME = value; }
        }

    }

    public partial class PTC_DG_BULIROUTE_RECORD_3 {
        private string thisTRACK = "";
        private string thisSTART_DISTRICT = "";
        private string thisSTART_MILEPOST = "";
        private string thisEND_DISTRICT = "";
        private string thisEND_MILEPOST = "";

        public string TRACK {
            get { return this.thisTRACK; }
            set { this.thisTRACK = value; }
        }

        public string START_DISTRICT {
            get { return this.thisSTART_DISTRICT; }
            set { this.thisSTART_DISTRICT = value; }
        }

        public string START_MILEPOST {
            get { return this.thisSTART_MILEPOST; }
            set { this.thisSTART_MILEPOST = value; }
        }

        public string END_DISTRICT {
            get { return this.thisEND_DISTRICT; }
            set { this.thisEND_DISTRICT = value; }
        }

        public string END_MILEPOST {
            get { return this.thisEND_MILEPOST; }
            set { this.thisEND_MILEPOST = value; }
        }

    }

    public partial class PTC_DG_BULIROUTE_DISTRICT_RECORD_3 {
        private string thisROUTE_DISTRICT_NAME = "";

        public string ROUTE_DISTRICT_NAME {
            get { return this.thisROUTE_DISTRICT_NAME; }
            set { this.thisROUTE_DISTRICT_NAME = value; }
        }

    }

    public partial class PTC_DG_BULICROSSING_RECORD_3 {
        private string thisCROSSING_DISTRICT_NAME = "";

        public string CROSSING_DISTRICT_NAME {
            get { return this.thisCROSSING_DISTRICT_NAME; }
            set { this.thisCROSSING_DISTRICT_NAME = value; }
        }

    }

    public partial class PTC_DG_BULITEXT_RECORD_3 {
        private string thisTEXT_SEQUENCE = "";
        private string thisTEXT = "";

        public string TEXT_SEQUENCE {
            get { return this.thisTEXT_SEQUENCE; }
            set { this.thisTEXT_SEQUENCE = value; }
        }

        public string TEXT {
            get { return this.thisTEXT; }
            set { this.thisTEXT = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class DG_BULI_3 {
        private object[] itemsField;

        [System.Xml.Serialization.XmlElementAttribute("HEADER", typeof(DG_BULIHEADER_3), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]

        [System.Xml.Serialization.XmlElementAttribute("CONTENT", typeof(DG_BULICONTENT_3), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]


        public object[] Items {
            get {
                return this.itemsField;
            }
    	    set {
    	        this.itemsField = value;
    	    }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DG_BULIHEADER_3 {
        private DG_BULIHEADERHEADER_EVENT_DATE_3[] HEADER_EVENT_DATEField;
        private DG_BULIHEADERHEADER_EVENT_TIME_3[] HEADER_EVENT_TIMEField;
        private DG_BULIHEADERHEADER_MESSAGE_ID_3[] HEADER_MESSAGE_IDField;
        private DG_BULIHEADERHEADER_SEQUENCE_NUMBER_3[] HEADER_SEQUENCE_NUMBERField;
        private DG_BULIHEADERHEADER_MESSAGE_VERSION_3[] HEADER_MESSAGE_VERSIONField;
        private DG_BULIHEADERHEADER_MESSAGE_REVISION_3[] HEADER_MESSAGE_REVISIONField;
        private DG_BULIHEADERHEADER_SOURCE_SYS_3[] HEADER_SOURCE_SYSField;
        private DG_BULIHEADERHEADER_DESTINATION_SYS_3[] HEADER_DESTINATION_SYSField;
        private DG_BULIHEADERHEADER_DISTRICT_NAME_3[] HEADER_DISTRICT_NAMEField;
        private DG_BULIHEADERHEADER_DISTRICT_SCAC_3[] HEADER_DISTRICT_SCACField;
        private DG_BULIHEADERHEADER_USER_ID_3[] HEADER_USER_IDField;

        [System.Xml.Serialization.XmlElementAttribute("HEADER_EVENT_DATE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DG_BULIHEADERHEADER_EVENT_DATE_3[] HEADER_EVENT_DATE {
            get { return this.HEADER_EVENT_DATEField; }
            set { this.HEADER_EVENT_DATEField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("HEADER_EVENT_TIME", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DG_BULIHEADERHEADER_EVENT_TIME_3[] HEADER_EVENT_TIME {
            get { return this.HEADER_EVENT_TIMEField; }
            set { this.HEADER_EVENT_TIMEField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("HEADER_MESSAGE_ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DG_BULIHEADERHEADER_MESSAGE_ID_3[] HEADER_MESSAGE_ID {
            get { return this.HEADER_MESSAGE_IDField; }
            set { this.HEADER_MESSAGE_IDField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("HEADER_SEQUENCE_NUMBER", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DG_BULIHEADERHEADER_SEQUENCE_NUMBER_3[] HEADER_SEQUENCE_NUMBER {
            get { return this.HEADER_SEQUENCE_NUMBERField; }
            set { this.HEADER_SEQUENCE_NUMBERField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("HEADER_MESSAGE_VERSION", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DG_BULIHEADERHEADER_MESSAGE_VERSION_3[] HEADER_MESSAGE_VERSION {
            get { return this.HEADER_MESSAGE_VERSIONField; }
            set { this.HEADER_MESSAGE_VERSIONField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("HEADER_MESSAGE_REVISION", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DG_BULIHEADERHEADER_MESSAGE_REVISION_3[] HEADER_MESSAGE_REVISION {
            get { return this.HEADER_MESSAGE_REVISIONField; }
            set { this.HEADER_MESSAGE_REVISIONField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("HEADER_SOURCE_SYS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DG_BULIHEADERHEADER_SOURCE_SYS_3[] HEADER_SOURCE_SYS {
            get { return this.HEADER_SOURCE_SYSField; }
            set { this.HEADER_SOURCE_SYSField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("HEADER_DESTINATION_SYS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DG_BULIHEADERHEADER_DESTINATION_SYS_3[] HEADER_DESTINATION_SYS {
            get { return this.HEADER_DESTINATION_SYSField; }
            set { this.HEADER_DESTINATION_SYSField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("HEADER_DISTRICT_NAME", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DG_BULIHEADERHEADER_DISTRICT_NAME_3[] HEADER_DISTRICT_NAME {
            get { return this.HEADER_DISTRICT_NAMEField; }
            set { this.HEADER_DISTRICT_NAMEField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("HEADER_DISTRICT_SCAC", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DG_BULIHEADERHEADER_DISTRICT_SCAC_3[] HEADER_DISTRICT_SCAC {
            get { return this.HEADER_DISTRICT_SCACField; }
            set { this.HEADER_DISTRICT_SCACField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("HEADER_USER_ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DG_BULIHEADERHEADER_USER_ID_3[] HEADER_USER_ID {
            get { return this.HEADER_USER_IDField; }
            set { this.HEADER_USER_IDField = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DG_BULIHEADERHEADER_EVENT_DATE_3 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DG_BULIHEADERHEADER_EVENT_TIME_3 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DG_BULIHEADERHEADER_MESSAGE_ID_3 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DG_BULIHEADERHEADER_SEQUENCE_NUMBER_3 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DG_BULIHEADERHEADER_MESSAGE_VERSION_3 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DG_BULIHEADERHEADER_MESSAGE_REVISION_3 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DG_BULIHEADERHEADER_SOURCE_SYS_3 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DG_BULIHEADERHEADER_DESTINATION_SYS_3 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DG_BULIHEADERHEADER_DISTRICT_NAME_3 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DG_BULIHEADERHEADER_DISTRICT_SCAC_3 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DG_BULIHEADERHEADER_USER_ID_3 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DG_BULICONTENT_3 {
        private DG_BULICONTENTBULLETIN_ITEM_NUMBER_3[] BULLETIN_ITEM_NUMBERField;
        private DG_BULICONTENTBULLETIN_ITEM_TYPE_3[] BULLETIN_ITEM_TYPEField;
        private DG_BULICONTENTFROM_LIMIT_3[] FROM_LIMITField;
        private DG_BULICONTENTTO_LIMIT_3[] TO_LIMITField;
        private DG_BULICONTENTEYE_CATCHER_TEXT_3[] EYE_CATCHER_TEXTField;
        private DG_BULICONTENTEFFECTIVE_DATE_3[] EFFECTIVE_DATEField;
        private DG_BULICONTENTEFFECTIVE_TIME_3[] EFFECTIVE_TIMEField;
        private DG_BULICONTENTEXPIRATION_DATE_3[] EXPIRATION_DATEField;
        private DG_BULICONTENTEXPIRATION_TIME_3[] EXPIRATION_TIMEField;
        private DG_BULICONTENTSPEED_3[] SPEEDField;
        private DG_BULICONTENTHEO_SPEED_RESTRICTION_3[] HEO_SPEED_RESTRICTIONField;
        private DG_BULICONTENTCONTACT_3[] CONTACTField;
        private DG_BULICONTENTTOD_FILTER_COUNT_3[] TOD_FILTER_COUNTField;
        private DG_BULICONTENTTOD_RECORD_3[] TOD_RECORDField;
        private DG_BULICONTENTROUTE_COUNT_3[] ROUTE_COUNTField;
        private DG_BULICONTENTROUTE_RECORD_3[] ROUTE_RECORDField;
        private DG_BULICONTENTROUTE_DISTRICT_COUNT_3[] ROUTE_DISTRICT_COUNTField;
        private DG_BULICONTENTROUTE_DISTRICT_RECORD_3[] ROUTE_DISTRICT_RECORDField;
        private DG_BULICONTENTCROSSING_ID_3[] CROSSING_IDField;
        private DG_BULICONTENTCROSSING_DISTRICT_COUNT_3[] CROSSING_DISTRICT_COUNTField;
        private DG_BULICONTENTCROSSING_RECORD_3[] CROSSING_RECORDField;
        private DG_BULICONTENTLINE_COUNT_3[] LINE_COUNTField;
        private DG_BULICONTENTTEXT_RECORD_3[] TEXT_RECORDField;

        [System.Xml.Serialization.XmlElementAttribute("BULLETIN_ITEM_NUMBER", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DG_BULICONTENTBULLETIN_ITEM_NUMBER_3[] BULLETIN_ITEM_NUMBER {
            get { return this.BULLETIN_ITEM_NUMBERField; }
            set { this.BULLETIN_ITEM_NUMBERField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("BULLETIN_ITEM_TYPE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DG_BULICONTENTBULLETIN_ITEM_TYPE_3[] BULLETIN_ITEM_TYPE {
            get { return this.BULLETIN_ITEM_TYPEField; }
            set { this.BULLETIN_ITEM_TYPEField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("FROM_LIMIT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DG_BULICONTENTFROM_LIMIT_3[] FROM_LIMIT {
            get { return this.FROM_LIMITField; }
            set { this.FROM_LIMITField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("TO_LIMIT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DG_BULICONTENTTO_LIMIT_3[] TO_LIMIT {
            get { return this.TO_LIMITField; }
            set { this.TO_LIMITField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("EYE_CATCHER_TEXT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DG_BULICONTENTEYE_CATCHER_TEXT_3[] EYE_CATCHER_TEXT {
            get { return this.EYE_CATCHER_TEXTField; }
            set { this.EYE_CATCHER_TEXTField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("EFFECTIVE_DATE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DG_BULICONTENTEFFECTIVE_DATE_3[] EFFECTIVE_DATE {
            get { return this.EFFECTIVE_DATEField; }
            set { this.EFFECTIVE_DATEField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("EFFECTIVE_TIME", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DG_BULICONTENTEFFECTIVE_TIME_3[] EFFECTIVE_TIME {
            get { return this.EFFECTIVE_TIMEField; }
            set { this.EFFECTIVE_TIMEField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("EXPIRATION_DATE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DG_BULICONTENTEXPIRATION_DATE_3[] EXPIRATION_DATE {
            get { return this.EXPIRATION_DATEField; }
            set { this.EXPIRATION_DATEField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("EXPIRATION_TIME", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DG_BULICONTENTEXPIRATION_TIME_3[] EXPIRATION_TIME {
            get { return this.EXPIRATION_TIMEField; }
            set { this.EXPIRATION_TIMEField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("SPEED", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DG_BULICONTENTSPEED_3[] SPEED {
            get { return this.SPEEDField; }
            set { this.SPEEDField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("HEO_SPEED_RESTRICTION", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DG_BULICONTENTHEO_SPEED_RESTRICTION_3[] HEO_SPEED_RESTRICTION {
            get { return this.HEO_SPEED_RESTRICTIONField; }
            set { this.HEO_SPEED_RESTRICTIONField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("CONTACT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DG_BULICONTENTCONTACT_3[] CONTACT {
            get { return this.CONTACTField; }
            set { this.CONTACTField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("TOD_FILTER_COUNT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DG_BULICONTENTTOD_FILTER_COUNT_3[] TOD_FILTER_COUNT {
            get { return this.TOD_FILTER_COUNTField; }
            set { this.TOD_FILTER_COUNTField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("TOD_RECORD", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DG_BULICONTENTTOD_RECORD_3[] TOD_RECORD {
            get { return this.TOD_RECORDField; }
            set { this.TOD_RECORDField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("ROUTE_COUNT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DG_BULICONTENTROUTE_COUNT_3[] ROUTE_COUNT {
            get { return this.ROUTE_COUNTField; }
            set { this.ROUTE_COUNTField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("ROUTE_RECORD", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DG_BULICONTENTROUTE_RECORD_3[] ROUTE_RECORD {
            get { return this.ROUTE_RECORDField; }
            set { this.ROUTE_RECORDField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("ROUTE_DISTRICT_COUNT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DG_BULICONTENTROUTE_DISTRICT_COUNT_3[] ROUTE_DISTRICT_COUNT {
            get { return this.ROUTE_DISTRICT_COUNTField; }
            set { this.ROUTE_DISTRICT_COUNTField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("ROUTE_DISTRICT_RECORD", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DG_BULICONTENTROUTE_DISTRICT_RECORD_3[] ROUTE_DISTRICT_RECORD {
            get { return this.ROUTE_DISTRICT_RECORDField; }
            set { this.ROUTE_DISTRICT_RECORDField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("CROSSING_ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DG_BULICONTENTCROSSING_ID_3[] CROSSING_ID {
            get { return this.CROSSING_IDField; }
            set { this.CROSSING_IDField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("CROSSING_DISTRICT_COUNT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DG_BULICONTENTCROSSING_DISTRICT_COUNT_3[] CROSSING_DISTRICT_COUNT {
            get { return this.CROSSING_DISTRICT_COUNTField; }
            set { this.CROSSING_DISTRICT_COUNTField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("CROSSING_RECORD", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DG_BULICONTENTCROSSING_RECORD_3[] CROSSING_RECORD {
            get { return this.CROSSING_RECORDField; }
            set { this.CROSSING_RECORDField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("LINE_COUNT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DG_BULICONTENTLINE_COUNT_3[] LINE_COUNT {
            get { return this.LINE_COUNTField; }
            set { this.LINE_COUNTField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("TEXT_RECORD", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DG_BULICONTENTTEXT_RECORD_3[] TEXT_RECORD {
            get { return this.TEXT_RECORDField; }
            set { this.TEXT_RECORDField = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DG_BULICONTENTBULLETIN_ITEM_NUMBER_3 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DG_BULICONTENTBULLETIN_ITEM_TYPE_3 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DG_BULICONTENTFROM_LIMIT_3 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DG_BULICONTENTTO_LIMIT_3 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DG_BULICONTENTEYE_CATCHER_TEXT_3 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DG_BULICONTENTEFFECTIVE_DATE_3 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DG_BULICONTENTEFFECTIVE_TIME_3 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DG_BULICONTENTEXPIRATION_DATE_3 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DG_BULICONTENTEXPIRATION_TIME_3 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DG_BULICONTENTSPEED_3 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DG_BULICONTENTHEO_SPEED_RESTRICTION_3 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DG_BULICONTENTCONTACT_3 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DG_BULICONTENTTOD_FILTER_COUNT_3 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DG_BULICONTENTROUTE_COUNT_3 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DG_BULICONTENTROUTE_DISTRICT_COUNT_3 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DG_BULICONTENTCROSSING_ID_3 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DG_BULICONTENTCROSSING_DISTRICT_COUNT_3 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DG_BULICONTENTLINE_COUNT_3 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DG_BULICONTENTTOD_RECORD_3 {
        private DG_BULITOD_RECORDTOD_DAY_OF_WEEK_3[] TOD_DAY_OF_WEEKField;
        private DG_BULITOD_RECORDTOD_START_TIME_3[] TOD_START_TIMEField;
        private DG_BULITOD_RECORDTOD_END_TIME_3[] TOD_END_TIMEField;

        [System.Xml.Serialization.XmlElementAttribute("TOD_DAY_OF_WEEK", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DG_BULITOD_RECORDTOD_DAY_OF_WEEK_3[] TOD_DAY_OF_WEEK {
            get { return this.TOD_DAY_OF_WEEKField; }
            set { this.TOD_DAY_OF_WEEKField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("TOD_START_TIME", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DG_BULITOD_RECORDTOD_START_TIME_3[] TOD_START_TIME {
            get { return this.TOD_START_TIMEField; }
            set { this.TOD_START_TIMEField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("TOD_END_TIME", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DG_BULITOD_RECORDTOD_END_TIME_3[] TOD_END_TIME {
            get { return this.TOD_END_TIMEField; }
            set { this.TOD_END_TIMEField = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DG_BULITOD_RECORDTOD_DAY_OF_WEEK_3 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DG_BULITOD_RECORDTOD_START_TIME_3 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DG_BULITOD_RECORDTOD_END_TIME_3 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DG_BULICONTENTROUTE_RECORD_3 {
        private DG_BULIROUTE_RECORDTRACK_3[] TRACKField;
        private DG_BULIROUTE_RECORDSTART_DISTRICT_3[] START_DISTRICTField;
        private DG_BULIROUTE_RECORDSTART_MILEPOST_3[] START_MILEPOSTField;
        private DG_BULIROUTE_RECORDEND_DISTRICT_3[] END_DISTRICTField;
        private DG_BULIROUTE_RECORDEND_MILEPOST_3[] END_MILEPOSTField;

        [System.Xml.Serialization.XmlElementAttribute("TRACK", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DG_BULIROUTE_RECORDTRACK_3[] TRACK {
            get { return this.TRACKField; }
            set { this.TRACKField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("START_DISTRICT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DG_BULIROUTE_RECORDSTART_DISTRICT_3[] START_DISTRICT {
            get { return this.START_DISTRICTField; }
            set { this.START_DISTRICTField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("START_MILEPOST", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DG_BULIROUTE_RECORDSTART_MILEPOST_3[] START_MILEPOST {
            get { return this.START_MILEPOSTField; }
            set { this.START_MILEPOSTField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("END_DISTRICT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DG_BULIROUTE_RECORDEND_DISTRICT_3[] END_DISTRICT {
            get { return this.END_DISTRICTField; }
            set { this.END_DISTRICTField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("END_MILEPOST", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DG_BULIROUTE_RECORDEND_MILEPOST_3[] END_MILEPOST {
            get { return this.END_MILEPOSTField; }
            set { this.END_MILEPOSTField = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DG_BULIROUTE_RECORDTRACK_3 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DG_BULIROUTE_RECORDSTART_DISTRICT_3 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DG_BULIROUTE_RECORDSTART_MILEPOST_3 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DG_BULIROUTE_RECORDEND_DISTRICT_3 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DG_BULIROUTE_RECORDEND_MILEPOST_3 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DG_BULICONTENTROUTE_DISTRICT_RECORD_3 {
        private DG_BULIROUTE_DISTRICT_RECORDROUTE_DISTRICT_NAME_3[] ROUTE_DISTRICT_NAMEField;

        [System.Xml.Serialization.XmlElementAttribute("ROUTE_DISTRICT_NAME", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DG_BULIROUTE_DISTRICT_RECORDROUTE_DISTRICT_NAME_3[] ROUTE_DISTRICT_NAME {
            get { return this.ROUTE_DISTRICT_NAMEField; }
            set { this.ROUTE_DISTRICT_NAMEField = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DG_BULIROUTE_DISTRICT_RECORDROUTE_DISTRICT_NAME_3 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DG_BULICONTENTCROSSING_RECORD_3 {
        private DG_BULICROSSING_RECORDCROSSING_DISTRICT_NAME_3[] CROSSING_DISTRICT_NAMEField;

        [System.Xml.Serialization.XmlElementAttribute("CROSSING_DISTRICT_NAME", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DG_BULICROSSING_RECORDCROSSING_DISTRICT_NAME_3[] CROSSING_DISTRICT_NAME {
            get { return this.CROSSING_DISTRICT_NAMEField; }
            set { this.CROSSING_DISTRICT_NAMEField = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DG_BULICROSSING_RECORDCROSSING_DISTRICT_NAME_3 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DG_BULICONTENTTEXT_RECORD_3 {
        private DG_BULITEXT_RECORDTEXT_SEQUENCE_3[] TEXT_SEQUENCEField;
        private DG_BULITEXT_RECORDTEXT_3[] TEXTField;

        [System.Xml.Serialization.XmlElementAttribute("TEXT_SEQUENCE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DG_BULITEXT_RECORDTEXT_SEQUENCE_3[] TEXT_SEQUENCE {
            get { return this.TEXT_SEQUENCEField; }
            set { this.TEXT_SEQUENCEField = value; }
        }

        [System.Xml.Serialization.XmlElementAttribute("TEXT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public DG_BULITEXT_RECORDTEXT_3[] TEXT {
            get { return this.TEXTField; }
            set { this.TEXTField = value; }
        }

    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DG_BULITEXT_RECORDTEXT_SEQUENCE_3 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class DG_BULITEXT_RECORDTEXT_3 {
       	[System.Xml.Serialization.XmlTextAttribute()]
	    public string Value {get; set;}
    }

}
