///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PDS_NS.Recording_Modules.Bulletins
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The IssueReplaceBulletin_BulletinInputRelayForm_NS recording.
    /// </summary>
    [TestModule("cd8f65f3-ef20-4340-afd4-bc9f121b3db1", ModuleType.Recording, 1)]
    public partial class IssueReplaceBulletin_BulletinInputRelayForm_NS : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::PDS_NS.PDS_NSRepository repository.
        /// </summary>
        public static global::PDS_NS.PDS_NSRepository repo = global::PDS_NS.PDS_NSRepository.Instance;

        static IssueReplaceBulletin_BulletinInputRelayForm_NS instance = new IssueReplaceBulletin_BulletinInputRelayForm_NS();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public IssueReplaceBulletin_BulletinInputRelayForm_NS()
        {
            bulletinSeedVoid = "";
            optionalReplaceBulletinSeed = "";
            pressComplete = "False";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static IssueReplaceBulletin_BulletinInputRelayForm_NS Instance
        {
            get { return instance; }
        }

#region Variables

        string _bulletinSeedVoid;

        /// <summary>
        /// Gets or sets the value of variable bulletinSeedVoid.
        /// </summary>
        [TestVariable("85574725-bca1-47fb-9457-5a87765b7e68")]
        public string bulletinSeedVoid
        {
            get { return _bulletinSeedVoid; }
            set { _bulletinSeedVoid = value; }
        }

        string _optionalReplaceBulletinSeed;

        /// <summary>
        /// Gets or sets the value of variable optionalReplaceBulletinSeed.
        /// </summary>
        [TestVariable("edcf793c-aa59-40e1-b4b7-8b290b332fac")]
        public string optionalReplaceBulletinSeed
        {
            get { return _optionalReplaceBulletinSeed; }
            set { _optionalReplaceBulletinSeed = value; }
        }

        string _pressComplete;

        /// <summary>
        /// Gets or sets the value of variable pressComplete.
        /// </summary>
        [TestVariable("5115e4c8-4994-49ae-9bc8-46faef970dfe")]
        public string pressComplete
        {
            get { return _pressComplete; }
            set { _pressComplete = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            UserCodeCollections.NS_Bulletin.NS_IssueReplaceBulletin_BulletinInputRelayForm(bulletinSeedVoid, optionalReplaceBulletinSeed, ValueConverter.ArgumentFromString<bool>("pressComplete", pressComplete));
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
