///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PDS_NS.Recording_Modules.Bulletins
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidatePendingBulletinCount_MainMenu_NS recording.
    /// </summary>
    [TestModule("225b2ba1-4404-4195-8a34-3d352b61689c", ModuleType.Recording, 1)]
    public partial class ValidatePendingBulletinCount_MainMenu_NS : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::PDS_NS.PDS_NSRepository repository.
        /// </summary>
        public static global::PDS_NS.PDS_NSRepository repo = global::PDS_NS.PDS_NSRepository.Instance;

        static ValidatePendingBulletinCount_MainMenu_NS instance = new ValidatePendingBulletinCount_MainMenu_NS();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidatePendingBulletinCount_MainMenu_NS()
        {
            expectedBulletinCount = "0";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidatePendingBulletinCount_MainMenu_NS Instance
        {
            get { return instance; }
        }

#region Variables

        string _expectedBulletinCount;

        /// <summary>
        /// Gets or sets the value of variable expectedBulletinCount.
        /// </summary>
        [TestVariable("1e675c7a-b763-4b36-8e0f-0a010df8b673")]
        public string expectedBulletinCount
        {
            get { return _expectedBulletinCount; }
            set { _expectedBulletinCount = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            UserCodeCollections.NS_Bulletin.NS_ValidatePendingBulletinCount_MainMenu(ValueConverter.ArgumentFromString<int>("expectedBulletinCount", expectedBulletinCount));
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
