///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PDS_NS.Recording_Modules.Assignments
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidateShiftTransitionIntervalExists_MasterShiftSchedule recording.
    /// </summary>
    [TestModule("60081a01-0e3d-4556-baaf-5bc6d08493e1", ModuleType.Recording, 1)]
    public partial class ValidateShiftTransitionIntervalExists_MasterShiftSchedule : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::PDS_NS.PDS_NSRepository repository.
        /// </summary>
        public static global::PDS_NS.PDS_NSRepository repo = global::PDS_NS.PDS_NSRepository.Instance;

        static ValidateShiftTransitionIntervalExists_MasterShiftSchedule instance = new ValidateShiftTransitionIntervalExists_MasterShiftSchedule();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidateShiftTransitionIntervalExists_MasterShiftSchedule()
        {
            transitionInterval = "";
            expectExists = "False";
            closeForm = "False";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidateShiftTransitionIntervalExists_MasterShiftSchedule Instance
        {
            get { return instance; }
        }

#region Variables

        string _transitionInterval;

        /// <summary>
        /// Gets or sets the value of variable transitionInterval.
        /// </summary>
        [TestVariable("8b07b6c8-bd9f-455f-914d-7c0027800a6f")]
        public string transitionInterval
        {
            get { return _transitionInterval; }
            set { _transitionInterval = value; }
        }

        string _expectExists;

        /// <summary>
        /// Gets or sets the value of variable expectExists.
        /// </summary>
        [TestVariable("7480af61-3b44-40a3-a197-517e4e74f8c0")]
        public string expectExists
        {
            get { return _expectExists; }
            set { _expectExists = value; }
        }

        string _closeForm;

        /// <summary>
        /// Gets or sets the value of variable closeForm.
        /// </summary>
        [TestVariable("4644584f-306a-44bc-9357-64dad09d9a52")]
        public string closeForm
        {
            get { return _closeForm; }
            set { _closeForm = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            UserCodeCollections.NS_Assignments.NS_ValidateShiftTransitionIntervalExists_MasterShiftSchedule(transitionInterval, ValueConverter.ArgumentFromString<bool>("expectExists", expectExists), ValueConverter.ArgumentFromString<bool>("closeForm", closeForm));
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
