///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PDS_NS.Recording_Modules.TerritoryTransfer
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidateTrainsNeedingBulletinsFromDispatcherTranferreportForm recording.
    /// </summary>
    [TestModule("d684481f-b927-4410-8299-d7c0c39c79f8", ModuleType.Recording, 1)]
    public partial class ValidateTrainsNeedingBulletinsFromDispatcherTranferreportForm : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::PDS_NS.PDS_NSRepository repository.
        /// </summary>
        public static global::PDS_NS.PDS_NSRepository repo = global::PDS_NS.PDS_NSRepository.Instance;

        static ValidateTrainsNeedingBulletinsFromDispatcherTranferreportForm instance = new ValidateTrainsNeedingBulletinsFromDispatcherTranferreportForm();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidateTrainsNeedingBulletinsFromDispatcherTranferreportForm()
        {
            closeForm = "False";
            optDivision = "";
            optLogicalPosition = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidateTrainsNeedingBulletinsFromDispatcherTranferreportForm Instance
        {
            get { return instance; }
        }

#region Variables

        string _closeForm;

        /// <summary>
        /// Gets or sets the value of variable closeForm.
        /// </summary>
        [TestVariable("483a5176-e487-4dae-98f6-4bba41f5aa24")]
        public string closeForm
        {
            get { return _closeForm; }
            set { _closeForm = value; }
        }

        string _optDivision;

        /// <summary>
        /// Gets or sets the value of variable optDivision.
        /// </summary>
        [TestVariable("089c65e3-d552-4d71-954e-2d78949f36fe")]
        public string optDivision
        {
            get { return _optDivision; }
            set { _optDivision = value; }
        }

        string _optLogicalPosition;

        /// <summary>
        /// Gets or sets the value of variable optLogicalPosition.
        /// </summary>
        [TestVariable("14cf57f7-bbaa-42c6-98a4-80376cb3792e")]
        public string optLogicalPosition
        {
            get { return _optLogicalPosition; }
            set { _optLogicalPosition = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            CodeUtils.NS_TerritoryTransfer_Validations.NS_ValidateTrainsNeedingBulletinsFromDispatcherTranferreportForm(optDivision, optLogicalPosition, ValueConverter.ArgumentFromString<bool>("closeForm", "False"));
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
