///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PDS_NS.Recording_Modules.Database
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ADMS_ValidateDG_AK01_ABF_OTC_MESSAGE recording.
    /// </summary>
    [TestModule("2e171278-9dca-465e-b6ea-89a4681d1f0b", ModuleType.Recording, 1)]
    public partial class ADMS_ValidateDG_AK01_ABF_OTC_MESSAGE : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::PDS_NS.PDS_NSRepository repository.
        /// </summary>
        public static global::PDS_NS.PDS_NSRepository repo = global::PDS_NS.PDS_NSRepository.Instance;

        static ADMS_ValidateDG_AK01_ABF_OTC_MESSAGE instance = new ADMS_ValidateDG_AK01_ABF_OTC_MESSAGE();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ADMS_ValidateDG_AK01_ABF_OTC_MESSAGE()
        {
            messageBeingAcknowledged = "";
            minutesBeforeNow = "";
            expectedCount = "";
            validateExists = "True";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ADMS_ValidateDG_AK01_ABF_OTC_MESSAGE Instance
        {
            get { return instance; }
        }

#region Variables

        string _messageBeingAcknowledged;

        /// <summary>
        /// Gets or sets the value of variable messageBeingAcknowledged.
        /// </summary>
        [TestVariable("9d80d698-1319-44ad-9068-b6a33d6d272a")]
        public string messageBeingAcknowledged
        {
            get { return _messageBeingAcknowledged; }
            set { _messageBeingAcknowledged = value; }
        }

        string _minutesBeforeNow;

        /// <summary>
        /// Gets or sets the value of variable minutesBeforeNow.
        /// </summary>
        [TestVariable("628c4022-f675-443c-bc08-8de35cf78805")]
        public string minutesBeforeNow
        {
            get { return _minutesBeforeNow; }
            set { _minutesBeforeNow = value; }
        }

        string _expectedCount;

        /// <summary>
        /// Gets or sets the value of variable expectedCount.
        /// </summary>
        [TestVariable("9fa9d141-31a5-4cf9-bdeb-ef978effa6eb")]
        public string expectedCount
        {
            get { return _expectedCount; }
            set { _expectedCount = value; }
        }

        string _validateExists;

        /// <summary>
        /// Gets or sets the value of variable validateExists.
        /// </summary>
        [TestVariable("13384bc9-abc5-498b-81e2-019a3ce83688")]
        public string validateExists
        {
            get { return _validateExists; }
            set { _validateExists = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            UserCodeCollections.NS_Oracle.NS_OracleValidation.NS_ValidateDG_AK01_ABF_OTC_MESSAGE_ADMS(messageBeingAcknowledged, minutesBeforeNow, expectedCount, ValueConverter.ArgumentFromString<bool>("validateExists", validateExists));
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
