///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PDS_NS.Recording_Modules.Database
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ADMS_Validate_ADMSABF_FBA_TAG_AUTHORITY_Backflow recording.
    /// </summary>
    [TestModule("d0b3107e-8453-40fb-a37b-ef286c695ab8", ModuleType.Recording, 1)]
    public partial class ADMS_Validate_ADMSABF_FBA_TAG_AUTHORITY_Backflow : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::PDS_NS.PDS_NSRepository repository.
        /// </summary>
        public static global::PDS_NS.PDS_NSRepository repo = global::PDS_NS.PDS_NSRepository.Instance;

        static ADMS_Validate_ADMSABF_FBA_TAG_AUTHORITY_Backflow instance = new ADMS_Validate_ADMSABF_FBA_TAG_AUTHORITY_Backflow();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ADMS_Validate_ADMSABF_FBA_TAG_AUTHORITY_Backflow()
        {
            tagName = "";
            tagType = "";
            eventSubType = "";
            withInMinutes = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ADMS_Validate_ADMSABF_FBA_TAG_AUTHORITY_Backflow Instance
        {
            get { return instance; }
        }

#region Variables

        string _tagName;

        /// <summary>
        /// Gets or sets the value of variable tagName.
        /// </summary>
        [TestVariable("4a3b6511-1de6-455f-91fd-838d8b1dd4ae")]
        public string tagName
        {
            get { return _tagName; }
            set { _tagName = value; }
        }

        string _tagType;

        /// <summary>
        /// Gets or sets the value of variable tagType.
        /// </summary>
        [TestVariable("fd9fdb5b-8bb0-493f-867a-f3adefc01cd6")]
        public string tagType
        {
            get { return _tagType; }
            set { _tagType = value; }
        }

        string _eventSubType;

        /// <summary>
        /// Gets or sets the value of variable eventSubType.
        /// </summary>
        [TestVariable("7baa6ad2-b04f-4427-a360-36a1cf5795de")]
        public string eventSubType
        {
            get { return _eventSubType; }
            set { _eventSubType = value; }
        }

        string _withInMinutes;

        /// <summary>
        /// Gets or sets the value of variable withInMinutes.
        /// </summary>
        [TestVariable("32e80c75-1c1d-491a-8781-050dfc827d30")]
        public string withInMinutes
        {
            get { return _withInMinutes; }
            set { _withInMinutes = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            UserCodeCollections.NS_Oracle.NS_OracleValidation.NS_ValidateTags_Backflow(tagName, tagType, eventSubType, withInMinutes);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
