///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PDS_NS.Recording_Modules.Track_Authorities
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The NS_Validate_Box6 recording.
    /// </summary>
    [TestModule("e914ba4d-6884-4df2-9dbf-87032f8047cc", ModuleType.Recording, 1)]
    public partial class NS_Validate_Box6 : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::PDS_NS.PDS_NSRepository repository.
        /// </summary>
        public static global::PDS_NS.PDS_NSRepository repo = global::PDS_NS.PDS_NSRepository.Instance;

        static NS_Validate_Box6 instance = new NS_Validate_Box6();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public NS_Validate_Box6()
        {
            box6EngineSeed1 = "";
            box6Engine1Direction = "";
            box6EngineSeed2 = "";
            box6Engine2Direction = "";
            box6EngineSeed3 = "";
            box6EngineDirection3 = "";
            box6At = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static NS_Validate_Box6 Instance
        {
            get { return instance; }
        }

#region Variables

        string _box6EngineSeed1;

        /// <summary>
        /// Gets or sets the value of variable box6EngineSeed1.
        /// </summary>
        [TestVariable("69d2474c-3a7c-46f9-8288-a4367d7d78a9")]
        public string box6EngineSeed1
        {
            get { return _box6EngineSeed1; }
            set { _box6EngineSeed1 = value; }
        }

        string _box6Engine1Direction;

        /// <summary>
        /// Gets or sets the value of variable box6Engine1Direction.
        /// </summary>
        [TestVariable("a9cbec08-5ff9-4896-b69b-d3bbf42e6106")]
        public string box6Engine1Direction
        {
            get { return _box6Engine1Direction; }
            set { _box6Engine1Direction = value; }
        }

        string _box6EngineSeed2;

        /// <summary>
        /// Gets or sets the value of variable box6EngineSeed2.
        /// </summary>
        [TestVariable("9e853bce-d7fd-463b-ade8-643afcf92e6c")]
        public string box6EngineSeed2
        {
            get { return _box6EngineSeed2; }
            set { _box6EngineSeed2 = value; }
        }

        string _box6Engine2Direction;

        /// <summary>
        /// Gets or sets the value of variable box6Engine2Direction.
        /// </summary>
        [TestVariable("a4134ecc-773a-4e4f-95ff-40d84aac25ea")]
        public string box6Engine2Direction
        {
            get { return _box6Engine2Direction; }
            set { _box6Engine2Direction = value; }
        }

        string _box6EngineSeed3;

        /// <summary>
        /// Gets or sets the value of variable box6EngineSeed3.
        /// </summary>
        [TestVariable("2008ad8a-a6d8-4d7b-a9c7-6c32c9f7a05a")]
        public string box6EngineSeed3
        {
            get { return _box6EngineSeed3; }
            set { _box6EngineSeed3 = value; }
        }

        string _box6EngineDirection3;

        /// <summary>
        /// Gets or sets the value of variable box6EngineDirection3.
        /// </summary>
        [TestVariable("e871b36b-32c9-43d7-9060-3eb0a8c92102")]
        public string box6EngineDirection3
        {
            get { return _box6EngineDirection3; }
            set { _box6EngineDirection3 = value; }
        }

        string _box6At;

        /// <summary>
        /// Gets or sets the value of variable box6At.
        /// </summary>
        [TestVariable("2e6b5e0b-bfbf-4aad-ba04-5570ae916d38")]
        public string box6At
        {
            get { return _box6At; }
            set { _box6At = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            UserCodeCollections.NS_Authorities.NS_ValidateBox6(box6EngineSeed1, box6Engine1Direction, box6EngineSeed2, box6Engine2Direction, box6EngineSeed3, box6EngineDirection3, box6At);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
