///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PDS_NS.Recording_Modules.DRA
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The NS_AcknowledgeDRAPopup recording.
    /// </summary>
    [TestModule("5edeed3a-5ae1-4f9d-b41b-fd1f51d8e4ff", ModuleType.Recording, 1)]
    public partial class NS_AcknowledgeDRAPopup : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::PDS_NS.PDS_NSRepository repository.
        /// </summary>
        public static global::PDS_NS.PDS_NSRepository repo = global::PDS_NS.PDS_NSRepository.Instance;

        static NS_AcknowledgeDRAPopup instance = new NS_AcknowledgeDRAPopup();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public NS_AcknowledgeDRAPopup()
        {
            commentsText = "";
            validatePopupExists = "FALSE";
            validatePinkColor = "FALSE";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static NS_AcknowledgeDRAPopup Instance
        {
            get { return instance; }
        }

#region Variables

        string _commentsText;

        /// <summary>
        /// Gets or sets the value of variable commentsText.
        /// </summary>
        [TestVariable("70244c39-7386-47dc-b576-10d76488a1bf")]
        public string commentsText
        {
            get { return _commentsText; }
            set { _commentsText = value; }
        }

        string _validatePopupExists;

        /// <summary>
        /// Gets or sets the value of variable validatePopupExists.
        /// </summary>
        [TestVariable("29b54a66-855c-4928-aeff-2e4ab7450068")]
        public string validatePopupExists
        {
            get { return _validatePopupExists; }
            set { _validatePopupExists = value; }
        }

        string _validatePinkColor;

        /// <summary>
        /// Gets or sets the value of variable validatePinkColor.
        /// </summary>
        [TestVariable("5b506583-088e-417c-a57a-2867b84adc68")]
        public string validatePinkColor
        {
            get { return _validatePinkColor; }
            set { _validatePinkColor = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            UserCodeCollections.NS_DRA.NS_AcknowledgePopup(commentsText, ValueConverter.ArgumentFromString<bool>("validatePopupExists", validatePopupExists), ValueConverter.ArgumentFromString<bool>("validatePinkColor", validatePinkColor));
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
