///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;
using Env.Code_Utils;

namespace PDS_CORE.Recording_Modules
{
    public partial class resetDbs
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void resetDbsFunction(String labelName, String db, String type = "Label")
        {
            VMEnvironment vm = VMEnvironment.Instance();
            Env.Code_Utils.LinuxUtils.runStartupScript(vm, "resetDbs.sh", label, db, type);
        }

    }
}
