///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PDS_NS.Recording_Modules.Train_Schedule
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The CreateTrainScheduleHeader_UI recording.
    /// </summary>
    [TestModule("22ec41d3-1bd0-4ead-b7fe-60e84331e41c", ModuleType.Recording, 1)]
    public partial class CreateTrainScheduleHeader_UI : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::PDS_NS.PDS_NSRepository repository.
        /// </summary>
        public static global::PDS_NS.PDS_NSRepository repo = global::PDS_NS.PDS_NSRepository.Instance;

        static CreateTrainScheduleHeader_UI instance = new CreateTrainScheduleHeader_UI();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public CreateTrainScheduleHeader_UI()
        {
            trainSeed = "";
            section = "";
            scac = "";
            originDateDayOffset = "";
            trainGroup = "";
            trainCategory = "";
            reportingType = "";
            expectedFeedback = "";
            reset = "False";
            closeForm = "False";
            clearForm = "False";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static CreateTrainScheduleHeader_UI Instance
        {
            get { return instance; }
        }

#region Variables

        string _trainSeed;

        /// <summary>
        /// Gets or sets the value of variable trainSeed.
        /// </summary>
        [TestVariable("8332142a-555f-409b-9fe6-03b742c43311")]
        public string trainSeed
        {
            get { return _trainSeed; }
            set { _trainSeed = value; }
        }

        string _section;

        /// <summary>
        /// Gets or sets the value of variable section.
        /// </summary>
        [TestVariable("a4512ff6-83ac-46b7-8d80-0292dd42024b")]
        public string section
        {
            get { return _section; }
            set { _section = value; }
        }

        string _scac;

        /// <summary>
        /// Gets or sets the value of variable scac.
        /// </summary>
        [TestVariable("1ee3c8b2-ef4b-46ee-8760-91bc4e0e884a")]
        public string scac
        {
            get { return _scac; }
            set { _scac = value; }
        }

        string _originDateDayOffset;

        /// <summary>
        /// Gets or sets the value of variable originDateDayOffset.
        /// </summary>
        [TestVariable("f221f5cd-35ee-43da-9510-92ba6c57670a")]
        public string originDateDayOffset
        {
            get { return _originDateDayOffset; }
            set { _originDateDayOffset = value; }
        }

        string _trainGroup;

        /// <summary>
        /// Gets or sets the value of variable trainGroup.
        /// </summary>
        [TestVariable("2d640c50-19af-4852-873e-fe478d1f5bbd")]
        public string trainGroup
        {
            get { return _trainGroup; }
            set { _trainGroup = value; }
        }

        string _trainCategory;

        /// <summary>
        /// Gets or sets the value of variable trainCategory.
        /// </summary>
        [TestVariable("9d31ce98-daaf-4856-86d2-647d83973c58")]
        public string trainCategory
        {
            get { return _trainCategory; }
            set { _trainCategory = value; }
        }

        string _reportingType;

        /// <summary>
        /// Gets or sets the value of variable reportingType.
        /// </summary>
        [TestVariable("7e4df09b-c82e-4ad9-9380-b0c5f52908ad")]
        public string reportingType
        {
            get { return _reportingType; }
            set { _reportingType = value; }
        }

        string _expectedFeedback;

        /// <summary>
        /// Gets or sets the value of variable expectedFeedback.
        /// </summary>
        [TestVariable("b56cbb7d-a6c7-40ee-a79b-4d71b6b1f419")]
        public string expectedFeedback
        {
            get { return _expectedFeedback; }
            set { _expectedFeedback = value; }
        }

        string _reset;

        /// <summary>
        /// Gets or sets the value of variable reset.
        /// </summary>
        [TestVariable("a4e6e60b-dd51-42c2-9e72-be5823217de4")]
        public string reset
        {
            get { return _reset; }
            set { _reset = value; }
        }

        string _closeForm;

        /// <summary>
        /// Gets or sets the value of variable closeForm.
        /// </summary>
        [TestVariable("5258ca05-4414-4657-b8e0-1059577e7b9e")]
        public string closeForm
        {
            get { return _closeForm; }
            set { _closeForm = value; }
        }

        string _clearForm;

        /// <summary>
        /// Gets or sets the value of variable clearForm.
        /// </summary>
        [TestVariable("344c5e17-3e5e-40fe-b491-8556dbb1fc15")]
        public string clearForm
        {
            get { return _clearForm; }
            set { _clearForm = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            UserCodeCollections.NS_Trainsheet.NS_CreateTrainScheduleHeader_UI(trainSeed, section, scac, originDateDayOffset, trainGroup, trainCategory, reportingType, expectedFeedback, ValueConverter.ArgumentFromString<bool>("reset", reset), ValueConverter.ArgumentFromString<bool>("clearForm", clearForm), ValueConverter.ArgumentFromString<bool>("closeForm", closeForm));
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
