///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PDS_NS.Recording_Modules.Playback
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidateAuthorityNumberInPlaybackSummaryList recording.
    /// </summary>
    [TestModule("97f40ee5-a85a-434e-97c4-b9b17375f8ce", ModuleType.Recording, 1)]
    public partial class ValidateAuthorityNumberInPlaybackSummaryList : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::PDS_NS.PDS_NSRepository repository.
        /// </summary>
        public static global::PDS_NS.PDS_NSRepository repo = global::PDS_NS.PDS_NSRepository.Instance;

        static ValidateAuthorityNumberInPlaybackSummaryList instance = new ValidateAuthorityNumberInPlaybackSummaryList();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidateAuthorityNumberInPlaybackSummaryList()
        {
            AuthoritySeed = "";
            ValidateExist = "True";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidateAuthorityNumberInPlaybackSummaryList Instance
        {
            get { return instance; }
        }

#region Variables

        string _AuthoritySeed;

        /// <summary>
        /// Gets or sets the value of variable AuthoritySeed.
        /// </summary>
        [TestVariable("67e8efa1-c80b-49a9-80d7-1c6a766467fa")]
        public string AuthoritySeed
        {
            get { return _AuthoritySeed; }
            set { _AuthoritySeed = value; }
        }

        string _ValidateExist;

        /// <summary>
        /// Gets or sets the value of variable ValidateExist.
        /// </summary>
        [TestVariable("bb252c37-d527-4466-9a10-cf0905f36fa8")]
        public string ValidateExist
        {
            get { return _ValidateExist; }
            set { _ValidateExist = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            UserCodeCollections.NS_Playback.NS_ValidateAuthorityNumber_PlaybackSummaryList(AuthoritySeed, ValueConverter.ArgumentFromString<bool>("closeAuthoritySummaryList", ValidateExist));
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
