///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace PDS_NS.Recording_Modules.SystemConfiguration.TrackingParameter
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ModifyDepartureTimeInterval_TrackingParameter_NS recording.
    /// </summary>
    [TestModule("3a7fe5ba-443d-4473-91d3-f1f204f4f3fe", ModuleType.Recording, 1)]
    public partial class ModifyDepartureTimeInterval_TrackingParameter_NS : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::PDS_NS.PDS_NSRepository repository.
        /// </summary>
        public static global::PDS_NS.PDS_NSRepository repo = global::PDS_NS.PDS_NSRepository.Instance;

        static ModifyDepartureTimeInterval_TrackingParameter_NS instance = new ModifyDepartureTimeInterval_TrackingParameter_NS();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ModifyDepartureTimeInterval_TrackingParameter_NS()
        {
            departureListVisibility = "";
            departureEligibilityLimit = "";
            expectedFeedback = "";
            reset = "False";
            apply = "True";
            closeForm = "True";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ModifyDepartureTimeInterval_TrackingParameter_NS Instance
        {
            get { return instance; }
        }

#region Variables

        string _departureListVisibility;

        /// <summary>
        /// Gets or sets the value of variable departureListVisibility.
        /// </summary>
        [TestVariable("606688bf-f54b-49ed-9af2-bfcabe35b1ba")]
        public string departureListVisibility
        {
            get { return _departureListVisibility; }
            set { _departureListVisibility = value; }
        }

        string _departureEligibilityLimit;

        /// <summary>
        /// Gets or sets the value of variable departureEligibilityLimit.
        /// </summary>
        [TestVariable("cf02ef18-8bdb-4a7c-a8b7-b96bc6660b74")]
        public string departureEligibilityLimit
        {
            get { return _departureEligibilityLimit; }
            set { _departureEligibilityLimit = value; }
        }

        string _expectedFeedback;

        /// <summary>
        /// Gets or sets the value of variable expectedFeedback.
        /// </summary>
        [TestVariable("7ca21636-8000-45e5-abfb-43ec32fa5a13")]
        public string expectedFeedback
        {
            get { return _expectedFeedback; }
            set { _expectedFeedback = value; }
        }

        string _reset;

        /// <summary>
        /// Gets or sets the value of variable reset.
        /// </summary>
        [TestVariable("d062f221-870a-4866-b19a-b37b93ad5092")]
        public string reset
        {
            get { return _reset; }
            set { _reset = value; }
        }

        string _apply;

        /// <summary>
        /// Gets or sets the value of variable apply.
        /// </summary>
        [TestVariable("21639973-527f-45c3-819a-c3d60aded7f4")]
        public string apply
        {
            get { return _apply; }
            set { _apply = value; }
        }

        string _closeForm;

        /// <summary>
        /// Gets or sets the value of variable closeForm.
        /// </summary>
        [TestVariable("c0fc319e-c838-4edf-8ad9-f8f735d9ff6e")]
        public string closeForm
        {
            get { return _closeForm; }
            set { _closeForm = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 100;
            Delay.SpeedFactor = 1.00;

            Init();

            UserCodeCollections.NS_SystemConfiguration.NS_ModifyDepartureTimeInterval_TrackingParameter(departureListVisibility, departureEligibilityLimit, expectedFeedback, ValueConverter.ArgumentFromString<bool>("reset", reset), ValueConverter.ArgumentFromString<bool>("apply", apply), ValueConverter.ArgumentFromString<bool>("closeForm", closeForm));
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
