//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.IO;
using System.Net.Sockets;
using System.Threading;
using System.Xml;
using System.Xml.Serialization;
using STE.Code_Utils.MessageQueues;


// 
// This source code was auto-generated by xsd, Version=4.7.2556.0.
// 
namespace STE.Code_Utils.messages.MIS.CN
{
	public partial class MIS_ExternalAlertEvent {
		private string thisMSGINFO;
		private MIS_ExternalAlertEventHEADER thisHEADER;
		private MIS_ExternalAlertEventCONTENT thisCONTENT;

		public string MSGINFO {
			get { return this.thisMSGINFO; }
			set { this.thisMSGINFO = value; }
		}

		public MIS_ExternalAlertEventHEADER HEADER {
			get { return this.thisHEADER; }
			set { this.thisHEADER = value; }
		}

		public MIS_ExternalAlertEventCONTENT CONTENT {
			get { return this.thisCONTENT; }
			set { this.thisCONTENT = value; }
		}

		public static void createExternalAlertEvent(
			string protocolid,
			string msgid,
			string trace_id,
			string message_version,
			string alert_event_key,
			string alert_event_type,
			string device_type,
			string device_id,
			string milepost,
			string subdivision,
			string division,
			string direction,
			string start_time,
			string start_time_zone,
			string message_text
		) {

			MIS_ExternalAlertEvent externalAlertEvent = new MIS_ExternalAlertEvent();

			string temp = System.Environment.GetEnvironmentVariable("TEMP");
			XmlSerializer serializer;
			System.DateTime now = System.DateTime.Now;
			FileStream fs;
			string request = "";

			MIS_ExternalAlertEventHEADER header = new MIS_ExternalAlertEventHEADER();
			header.PROTOCOLID = protocolid;
			header.MSGID = msgid;
			header.TRACE_ID = trace_id;
			header.MESSAGE_VERSION = message_version;
			
			MIS_ExternalAlertEventCONTENT content = new MIS_ExternalAlertEventCONTENT();
			content.ALERT_EVENT_KEY = alert_event_key;
			content.ALERT_EVENT_TYPE = alert_event_type;
			content.DEVICE_TYPE = device_type;
			content.DEVICE_ID = device_id;
			content.MILEPOST = milepost;
			content.SUBDIVISION =subdivision;
			content.DIVISION = division;
			content.DIRECTION = direction;
			
			DateTime startTime = now.AddMinutes(Convert.ToDouble(start_time));
			content.START_DATE = startTime.ToString("MMddyyyy");
			content.START_TIME = startTime.ToString("HHmm");
			content.START_TIME_ZONE = start_time_zone;
			content.MESSAGE_TEXT = message_text;

			externalAlertEvent.HEADER = header;
			externalAlertEvent.CONTENT = content;

			ExternalAlertEvent externalalertevent = externalAlertEvent.toSerializableObject();
			fs = File.Create(temp+"/temp.request");
			serializer = new XmlSerializer(typeof(ExternalAlertEvent));
			var writer = new SteXmlTextWriter(fs);
			serializer.Serialize(writer, externalalertevent);
			fs.Close();

			request = File.ReadAllText(temp+"/temp.request");
			request = externalAlertEvent.toSteMessageHeader(request);
			System.IO.File.WriteAllText(SteUtils.getOutboundDir()+SteUtils.getFileName(), request);
		}
		
		public static void createExternalAlertEventRemote(
			string protocolid,
			string msgid,
			string trace_id,
			string message_version,
			string alert_event_key,
			string alert_event_type,
			string device_type,
			string device_id,
			string milepost,
			string subdivision,
			string division,
			string direction,
			string start_time,
			string start_time_zone,
			string message_text,
			string hostname
		) {

			int receiver_port = 2500;
			MIS_ExternalAlertEvent externalAlertEvent = new MIS_ExternalAlertEvent();

			string temp = System.Environment.GetEnvironmentVariable("TEMP");
			XmlSerializer serializer;
			System.DateTime now = System.DateTime.Now;
			FileStream fs;
			string request = "";

			MIS_ExternalAlertEventHEADER header = new MIS_ExternalAlertEventHEADER();
			header.PROTOCOLID = protocolid;
			header.MSGID = msgid;
			header.TRACE_ID = trace_id;
			header.MESSAGE_VERSION = message_version;
			
			MIS_ExternalAlertEventCONTENT content = new MIS_ExternalAlertEventCONTENT();
			content.ALERT_EVENT_KEY = alert_event_key;
			content.ALERT_EVENT_TYPE = alert_event_type;
			content.DEVICE_TYPE = device_type;
			content.DEVICE_ID = device_id;
			content.MILEPOST = milepost;
			content.SUBDIVISION =subdivision;
			content.DIVISION = division;
			content.DIRECTION = direction;
			
			DateTime startTime = now.AddMinutes(Convert.ToDouble(start_time));
			content.START_DATE = startTime.ToString("MMddyyyy");
			content.START_TIME = startTime.ToString("HHmm");
			content.START_TIME_ZONE = start_time_zone;
			content.MESSAGE_TEXT = message_text;

			externalAlertEvent.HEADER = header;
			externalAlertEvent.CONTENT = content;

			ExternalAlertEvent externalalertevent = externalAlertEvent.toSerializableObject();
			fs = File.Create(temp+"/temp.request");
			serializer = new XmlSerializer(typeof(ExternalAlertEvent));
			var writer = new SteXmlTextWriter(fs);
			serializer.Serialize(writer, externalalertevent);
			fs.Close();

			request = File.ReadAllText(temp+"/temp.request");
			request = externalAlertEvent.toSteMessageHeader(request,true);
			
			using(TcpClient tcp = new TcpClient(hostname, receiver_port)) {
				NetworkStream nw = tcp.GetStream();
				nw.ReadTimeout = 5000; //5 second timeout for read response
				Ranorex.Report.Info(String.Format("Encoding Message {0} for STE {1}:2500",request, hostname));
				//byte[] bytesToSend = UTF8Encoding.UTF8.GetBytes(request);
				Byte[] data = System.Text.Encoding.ASCII.GetBytes(request);
				//log to record we are sending exec
				nw.Write(data, 0, data.Length);
				
				Thread.Sleep(5);
				nw.Close();
			}
			
		}
		

		public static void createExternalAlertEventMsmq(
			string protocolid,
			string msgid,
			string trace_id,
			string message_version,
			string alert_event_key,
			string alert_event_type,
			string device_type,
			string device_id,
			string milepost,
			string subdivision,
			string division,
			string direction,
			string start_time,
			string start_time_zone,
			string message_text
		) {

			MIS_ExternalAlertEvent externalAlertEvent = new MIS_ExternalAlertEvent();

			string temp = System.Environment.GetEnvironmentVariable("TEMP");
			XmlSerializer serializer;
			System.DateTime now = System.DateTime.Now;
			string request = "";
			
			MIS_ExternalAlertEventHEADER header = new MIS_ExternalAlertEventHEADER();
			header.PROTOCOLID = protocolid;
			header.MSGID = msgid;
			header.TRACE_ID = trace_id;
			header.MESSAGE_VERSION = message_version;
			
			MIS_ExternalAlertEventCONTENT content = new MIS_ExternalAlertEventCONTENT();
			content.ALERT_EVENT_KEY = alert_event_key;
			content.ALERT_EVENT_TYPE = alert_event_type;
			content.DEVICE_TYPE = device_type;
			content.DEVICE_ID = device_id;
			content.MILEPOST = milepost;
			content.DIVISION = division;
			content.DIRECTION = direction;
			
			DateTime startTime = now.AddMinutes(Convert.ToDouble(start_time));
			content.START_DATE = startTime.ToString("MMddyyyy");
			content.START_TIME = startTime.ToString("HHmm");
			content.START_TIME_ZONE = start_time_zone;
			content.MESSAGE_TEXT = message_text;

			externalAlertEvent.HEADER = header;
			externalAlertEvent.CONTENT = content;

			ExternalAlertEvent externalalertevent = externalAlertEvent.toSerializableObject();
			serializer = new XmlSerializer(typeof(ExternalAlertEvent));
			StringWriter writer = new StringWriter();
			serializer.Serialize(writer, externalalertevent);
			request = externalAlertEvent.toSteMessageHeader(writer.ToString());
			SteMessageQueue.Instance().Send(request, "MIS-ExternalAlertEvent");
		}

		public ExternalAlertEvent toSerializableObject() {
			ExternalAlertEvent externalAlertEvent = new ExternalAlertEvent();
			externalAlertEvent.Items = new object[2];

			ExternalAlertEventHEADER header = new ExternalAlertEventHEADER();
			if (this.HEADER != null)
			{
				if (this.HEADER.PROTOCOLID != null) {
					header.PROTOCOLID = new ExternalAlertEventHEADERPROTOCOLID[1];
					ExternalAlertEventHEADERPROTOCOLID protocolid = new ExternalAlertEventHEADERPROTOCOLID();
					protocolid.Value = this.HEADER.PROTOCOLID;
					header.PROTOCOLID[0] = protocolid;
				}
				
				if (this.HEADER.MSGID != null) {
					header.MSGID = new ExternalAlertEventHEADERMSGID[1];
					ExternalAlertEventHEADERMSGID msgid = new ExternalAlertEventHEADERMSGID();
					msgid.Value = this.HEADER.MSGID;
					header.MSGID[0] = msgid;
				}
				
				if (this.HEADER.TRACE_ID != null) {
					header.TRACE_ID = new ExternalAlertEventHEADERTRACE_ID[1];
					ExternalAlertEventHEADERTRACE_ID trace_id = new ExternalAlertEventHEADERTRACE_ID();
					trace_id.Value = this.HEADER.TRACE_ID;
					header.TRACE_ID[0] = trace_id;
				}
				
				if (this.HEADER.MESSAGE_VERSION != null) {
					header.MESSAGE_VERSION = new ExternalAlertEventHEADERMESSAGE_VERSION[1];
					ExternalAlertEventHEADERMESSAGE_VERSION message_version = new ExternalAlertEventHEADERMESSAGE_VERSION();
					message_version.Value = this.HEADER.MESSAGE_VERSION;
					header.MESSAGE_VERSION[0] = message_version;
				}
			}

			ExternalAlertEventCONTENT content = new ExternalAlertEventCONTENT();
			if (this.CONTENT != null)
			{
				if (this.CONTENT.ALERT_EVENT_KEY != null) {
					content.ALERT_EVENT_KEY = new ExternalAlertEventCONTENTALERT_EVENT_KEY[1];
					ExternalAlertEventCONTENTALERT_EVENT_KEY alert_event_key = new ExternalAlertEventCONTENTALERT_EVENT_KEY();
					alert_event_key.Value = this.CONTENT.ALERT_EVENT_KEY;
					content.ALERT_EVENT_KEY[0] = alert_event_key;
				}
				
				if (this.CONTENT.ALERT_EVENT_TYPE != null) {
					content.ALERT_EVENT_TYPE = new ExternalAlertEventCONTENTALERT_EVENT_TYPE[1];
					ExternalAlertEventCONTENTALERT_EVENT_TYPE alert_event_type = new ExternalAlertEventCONTENTALERT_EVENT_TYPE();
					alert_event_type.Value = this.CONTENT.ALERT_EVENT_TYPE;
					content.ALERT_EVENT_TYPE[0] = alert_event_type;
				}
				
				if (this.CONTENT.DEVICE_TYPE != null) {
					content.DEVICE_TYPE = new ExternalAlertEventCONTENTDEVICE_TYPE[1];
					ExternalAlertEventCONTENTDEVICE_TYPE device_type = new ExternalAlertEventCONTENTDEVICE_TYPE();
					device_type.Value = this.CONTENT.DEVICE_TYPE;
					content.DEVICE_TYPE[0] = device_type;
				}
				
				if (this.CONTENT.DEVICE_ID != null) {
					content.DEVICE_ID = new ExternalAlertEventCONTENTDEVICE_ID[1];
					ExternalAlertEventCONTENTDEVICE_ID device_id = new ExternalAlertEventCONTENTDEVICE_ID();
					device_id.Value = this.CONTENT.DEVICE_ID;
					content.DEVICE_ID[0] = device_id;
				}
				
				if (this.CONTENT.MILEPOST != null) {
					content.MILEPOST = new ExternalAlertEventCONTENTMILEPOST[1];
					ExternalAlertEventCONTENTMILEPOST milepost = new ExternalAlertEventCONTENTMILEPOST();
					milepost.Value = this.CONTENT.MILEPOST;
					content.MILEPOST[0] = milepost;
				}
				
				if (this.CONTENT.SUBDIVISION != null) {
					content.SUBDIVISION = new ExternalAlertEventCONTENTSUBDIVISION[1];
					ExternalAlertEventCONTENTSUBDIVISION subdivision = new ExternalAlertEventCONTENTSUBDIVISION();
					subdivision.Value = this.CONTENT.SUBDIVISION;
					content.SUBDIVISION[0] = subdivision;
				}

				if (this.CONTENT.DIVISION != null) {
					content.DIVISION = new ExternalAlertEventCONTENTDIVISION[1];
					ExternalAlertEventCONTENTDIVISION division = new ExternalAlertEventCONTENTDIVISION();
					division.Value = this.CONTENT.DIVISION;
					content.DIVISION[0] = division;
				}
				
				if (this.CONTENT.DIRECTION != null) {
					content.DIRECTION = new ExternalAlertEventCONTENTDIRECTION[1];
					ExternalAlertEventCONTENTDIRECTION direction = new ExternalAlertEventCONTENTDIRECTION();
					direction.Value = this.CONTENT.DIRECTION;
					content.DIRECTION[0] = direction;
				}
				
				if (this.CONTENT.START_DATE != null) {
					content.START_DATE = new ExternalAlertEventCONTENTSTART_DATE[1];
					ExternalAlertEventCONTENTSTART_DATE start_date = new ExternalAlertEventCONTENTSTART_DATE();
					start_date.Value = this.CONTENT.START_DATE;
					content.START_DATE[0] = start_date;
				}
				
				if (this.CONTENT.START_TIME != null) {
					content.START_TIME = new ExternalAlertEventCONTENTSTART_TIME[1];
					ExternalAlertEventCONTENTSTART_TIME start_time = new ExternalAlertEventCONTENTSTART_TIME();
					start_time.Value = this.CONTENT.START_TIME;
					content.START_TIME[0] = start_time;
				}
				
				if (this.CONTENT.START_TIME_ZONE != null) {
					content.START_TIME_ZONE = new ExternalAlertEventCONTENTSTART_TIME_ZONE[1];
					ExternalAlertEventCONTENTSTART_TIME_ZONE start_time_zone = new ExternalAlertEventCONTENTSTART_TIME_ZONE();
					start_time_zone.Value = this.CONTENT.START_TIME_ZONE;
					content.START_TIME_ZONE[0] = start_time_zone;
				}
				
				if (this.CONTENT.MESSAGE_TEXT != null) {
					content.MESSAGE_TEXT = new ExternalAlertEventCONTENTMESSAGE_TEXT[1];
					ExternalAlertEventCONTENTMESSAGE_TEXT message_text = new ExternalAlertEventCONTENTMESSAGE_TEXT();
					message_text.Value = this.CONTENT.MESSAGE_TEXT;
					content.MESSAGE_TEXT[0] = message_text;
				}
			}

			externalAlertEvent.Items[0] = header;
			externalAlertEvent.Items[1] = content;
			return externalAlertEvent;
		}

		public string toSteMessageHeader(string serializedXml,bool remote = false) {
			int from = serializedXml.IndexOf("<CONTENT>") + "<CONTENT>".Length;
			int to   = serializedXml.LastIndexOf("</CONTENT>");
			
			string header="";
			if (!remote)
			{
				header = "PASSTHRU,MEXTALT,";
			}
			else
			{
				header = "RanorexAgent:PASSTHRU,MEXTALT,";
			}
			
			
			string result = header + serializedXml.Substring(from, to-from);
			
			return result;
		}
	}

	public partial class MIS_ExternalAlertEventHEADER {
		private string thisPROTOCOLID = "";
		private string thisMSGID = "";
		private string thisTRACE_ID = "";
		private string thisMESSAGE_VERSION = "";

		public string PROTOCOLID {
			get { return this.thisPROTOCOLID; }
			set { this.thisPROTOCOLID = value; }
		}

		public string MSGID {
			get { return this.thisMSGID; }
			set { this.thisMSGID = value; }
		}

		public string TRACE_ID {
			get { return this.thisTRACE_ID; }
			set { this.thisTRACE_ID = value; }
		}

		public string MESSAGE_VERSION {
			get { return this.thisMESSAGE_VERSION; }
			set { this.thisMESSAGE_VERSION = value; }
		}

	}

	public partial class MIS_ExternalAlertEventCONTENT {
		private string thisALERT_EVENT_KEY = "";
		private string thisALERT_EVENT_TYPE = "";
		private string thisDEVICE_TYPE = "";
		private string thisDEVICE_ID = "";
		private string thisMILEPOST = "";
		private string thisSUBDIVISION = "";
		private string thisDIVISION = "";
		private string thisDIRECTION = "";
		private string thisSTART_DATE = "";
		private string thisSTART_TIME = "";
		private string thisSTART_TIME_ZONE = "";
		private string thisMESSAGE_TEXT = "";

		public string ALERT_EVENT_KEY {
			get { return this.thisALERT_EVENT_KEY; }
			set { this.thisALERT_EVENT_KEY = value; }
		}

		public string ALERT_EVENT_TYPE {
			get { return this.thisALERT_EVENT_TYPE; }
			set { this.thisALERT_EVENT_TYPE = value; }
		}

		public string DEVICE_TYPE {
			get { return this.thisDEVICE_TYPE; }
			set { this.thisDEVICE_TYPE = value; }
		}

		public string DEVICE_ID {
			get { return this.thisDEVICE_ID; }
			set { this.thisDEVICE_ID = value; }
		}

		public string MILEPOST {
			get { return this.thisMILEPOST; }
			set { this.thisMILEPOST = value; }
		}

		public string SUBDIVISION {
			get { return this.thisSUBDIVISION; }
			set { this.thisSUBDIVISION = value; }
		}
		
		public string DIVISION {
			get { return this.thisDIVISION; }
			set { this.thisDIVISION = value; }
		}

		public string DIRECTION {
			get { return this.thisDIRECTION; }
			set { this.thisDIRECTION = value; }
		}

		public string START_DATE {
			get { return this.thisSTART_DATE; }
			set { this.thisSTART_DATE = value; }
		}

		public string START_TIME {
			get { return this.thisSTART_TIME; }
			set { this.thisSTART_TIME = value; }
		}

		public string START_TIME_ZONE {
			get { return this.thisSTART_TIME_ZONE; }
			set { this.thisSTART_TIME_ZONE = value; }
		}

		public string MESSAGE_TEXT {
			get { return this.thisMESSAGE_TEXT; }
			set { this.thisMESSAGE_TEXT = value; }
		}

	}


	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
	[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
	public partial class ExternalAlertEvent  {
		
		private object[] itemsField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("CONTENT", typeof(ExternalAlertEventCONTENT), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[System.Xml.Serialization.XmlElementAttribute("HEADER", typeof(ExternalAlertEventHEADER), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		[System.Xml.Serialization.XmlElementAttribute("MSGINFO", typeof(ExternalAlertEventMSGINFO), Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public object[] Items {
			get {
				return this.itemsField;
			}
			set {
				this.itemsField = value;
			}
		}
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
	public partial class ExternalAlertEventCONTENT {
		
		private ExternalAlertEventCONTENTALERT_EVENT_KEY[] aLERT_EVENT_KEYField;
		
		private ExternalAlertEventCONTENTALERT_EVENT_TYPE[] aLERT_EVENT_TYPEField;
		
		private ExternalAlertEventCONTENTDEVICE_TYPE[] dEVICE_TYPEField;
		
		private ExternalAlertEventCONTENTDEVICE_ID[] dEVICE_IDField;
		
		private ExternalAlertEventCONTENTMILEPOST[] mILEPOSTField;
		
		private ExternalAlertEventCONTENTSUBDIVISION[] sUBDIVISIONField;
		
		private ExternalAlertEventCONTENTDIVISION[] dIVISIONField;
		
		private ExternalAlertEventCONTENTDIRECTION[] dIRECTIONField;
		
		private ExternalAlertEventCONTENTSTART_DATE[] sTART_DATEField;
		
		private ExternalAlertEventCONTENTSTART_TIME[] sTART_TIMEField;
		
		private ExternalAlertEventCONTENTSTART_TIME_ZONE[] sTART_TIME_ZONEField;
		
		private ExternalAlertEventCONTENTMESSAGE_TEXT[] mESSAGE_TEXTField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("ALERT_EVENT_KEY", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public ExternalAlertEventCONTENTALERT_EVENT_KEY[] ALERT_EVENT_KEY {
			get {
				return this.aLERT_EVENT_KEYField;
			}
			set {
				this.aLERT_EVENT_KEYField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("ALERT_EVENT_TYPE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public ExternalAlertEventCONTENTALERT_EVENT_TYPE[] ALERT_EVENT_TYPE {
			get {
				return this.aLERT_EVENT_TYPEField;
			}
			set {
				this.aLERT_EVENT_TYPEField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("DEVICE_TYPE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public ExternalAlertEventCONTENTDEVICE_TYPE[] DEVICE_TYPE {
			get {
				return this.dEVICE_TYPEField;
			}
			set {
				this.dEVICE_TYPEField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("DEVICE_ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public ExternalAlertEventCONTENTDEVICE_ID[] DEVICE_ID {
			get {
				return this.dEVICE_IDField;
			}
			set {
				this.dEVICE_IDField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("MILEPOST", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public ExternalAlertEventCONTENTMILEPOST[] MILEPOST {
			get {
				return this.mILEPOSTField;
			}
			set {
				this.mILEPOSTField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("SUBDIVISION", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public ExternalAlertEventCONTENTSUBDIVISION[] SUBDIVISION {
			get {
				return this.sUBDIVISIONField;
			}
			set {
				this.sUBDIVISIONField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("DIVISION", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public ExternalAlertEventCONTENTDIVISION[] DIVISION {
			get {
				return this.dIVISIONField;
			}
			set {
				this.dIVISIONField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("DIRECTION", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public ExternalAlertEventCONTENTDIRECTION[] DIRECTION {
			get {
				return this.dIRECTIONField;
			}
			set {
				this.dIRECTIONField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("START_DATE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public ExternalAlertEventCONTENTSTART_DATE[] START_DATE {
			get {
				return this.sTART_DATEField;
			}
			set {
				this.sTART_DATEField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("START_TIME", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public ExternalAlertEventCONTENTSTART_TIME[] START_TIME {
			get {
				return this.sTART_TIMEField;
			}
			set {
				this.sTART_TIMEField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("START_TIME_ZONE", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public ExternalAlertEventCONTENTSTART_TIME_ZONE[] START_TIME_ZONE {
			get {
				return this.sTART_TIME_ZONEField;
			}
			set {
				this.sTART_TIME_ZONEField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("MESSAGE_TEXT", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public ExternalAlertEventCONTENTMESSAGE_TEXT[] MESSAGE_TEXT {
			get {
				return this.mESSAGE_TEXTField;
			}
			set {
				this.mESSAGE_TEXTField = value;
			}
		}
		
		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value {get; set;}
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
	public partial class ExternalAlertEventCONTENTALERT_EVENT_KEY {
		
		private string pds_msg_lengthField;
		
		private string pds_msg_loopField;
		
		private string pds_msg_mvcelementnameField;
		
		private string pds_msg_reqdField;
		
		private string pds_msg_businesskeyField;
		
		private string pds_msg_alphanumericField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_length {
			get {
				return this.pds_msg_lengthField;
			}
			set {
				this.pds_msg_lengthField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_loop {
			get {
				return this.pds_msg_loopField;
			}
			set {
				this.pds_msg_loopField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_mvcelementname {
			get {
				return this.pds_msg_mvcelementnameField;
			}
			set {
				this.pds_msg_mvcelementnameField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_reqd {
			get {
				return this.pds_msg_reqdField;
			}
			set {
				this.pds_msg_reqdField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_businesskey {
			get {
				return this.pds_msg_businesskeyField;
			}
			set {
				this.pds_msg_businesskeyField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_alphanumeric {
			get {
				return this.pds_msg_alphanumericField;
			}
			set {
				this.pds_msg_alphanumericField = value;
			}
		}
		
		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value {get; set;}
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
	public partial class ExternalAlertEventCONTENTALERT_EVENT_TYPE {
		
		private string pds_msg_lengthField;
		
		private string pds_msg_loopField;
		
		private string pds_msg_mvcelementnameField;
		
		private string pds_msg_reqdField;
		
		private string pds_msg_businesskeyField;
		
		private string pds_msg_alphanumericField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_length {
			get {
				return this.pds_msg_lengthField;
			}
			set {
				this.pds_msg_lengthField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_loop {
			get {
				return this.pds_msg_loopField;
			}
			set {
				this.pds_msg_loopField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_mvcelementname {
			get {
				return this.pds_msg_mvcelementnameField;
			}
			set {
				this.pds_msg_mvcelementnameField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_reqd {
			get {
				return this.pds_msg_reqdField;
			}
			set {
				this.pds_msg_reqdField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_businesskey {
			get {
				return this.pds_msg_businesskeyField;
			}
			set {
				this.pds_msg_businesskeyField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_alphanumeric {
			get {
				return this.pds_msg_alphanumericField;
			}
			set {
				this.pds_msg_alphanumericField = value;
			}
		}
		
		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value {get; set;}
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
	public partial class ExternalAlertEventCONTENTDEVICE_TYPE {
		
		private string pds_msg_lengthField;
		
		private string pds_msg_loopField;
		
		private string pds_msg_mvcelementnameField;
		
		private string pds_msg_reqdField;
		
		private string pds_msg_businesskeyField;
		
		private string pds_msg_alphanumericField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_length {
			get {
				return this.pds_msg_lengthField;
			}
			set {
				this.pds_msg_lengthField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_loop {
			get {
				return this.pds_msg_loopField;
			}
			set {
				this.pds_msg_loopField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_mvcelementname {
			get {
				return this.pds_msg_mvcelementnameField;
			}
			set {
				this.pds_msg_mvcelementnameField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_reqd {
			get {
				return this.pds_msg_reqdField;
			}
			set {
				this.pds_msg_reqdField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_businesskey {
			get {
				return this.pds_msg_businesskeyField;
			}
			set {
				this.pds_msg_businesskeyField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_alphanumeric {
			get {
				return this.pds_msg_alphanumericField;
			}
			set {
				this.pds_msg_alphanumericField = value;
			}
		}
		
		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value {get; set;}
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
	public partial class ExternalAlertEventCONTENTDEVICE_ID {
		
		private string pds_msg_lengthField;
		
		private string pds_msg_loopField;
		
		private string pds_msg_mvcelementnameField;
		
		private string pds_msg_reqdField;
		
		private string pds_msg_businesskeyField;
		
		private string pds_msg_alphanumericField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_length {
			get {
				return this.pds_msg_lengthField;
			}
			set {
				this.pds_msg_lengthField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_loop {
			get {
				return this.pds_msg_loopField;
			}
			set {
				this.pds_msg_loopField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_mvcelementname {
			get {
				return this.pds_msg_mvcelementnameField;
			}
			set {
				this.pds_msg_mvcelementnameField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_reqd {
			get {
				return this.pds_msg_reqdField;
			}
			set {
				this.pds_msg_reqdField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_businesskey {
			get {
				return this.pds_msg_businesskeyField;
			}
			set {
				this.pds_msg_businesskeyField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_alphanumeric {
			get {
				return this.pds_msg_alphanumericField;
			}
			set {
				this.pds_msg_alphanumericField = value;
			}
		}
		
		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value {get; set;}
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
	public partial class ExternalAlertEventCONTENTMILEPOST {
		
		private string pds_msg_lengthField;
		
		private string pds_msg_loopField;
		
		private string pds_msg_mvcelementnameField;
		
		private string pds_msg_reqdField;
		
		private string pds_msg_businesskeyField;
		
		private string pds_msg_alphanumericField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_length {
			get {
				return this.pds_msg_lengthField;
			}
			set {
				this.pds_msg_lengthField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_loop {
			get {
				return this.pds_msg_loopField;
			}
			set {
				this.pds_msg_loopField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_mvcelementname {
			get {
				return this.pds_msg_mvcelementnameField;
			}
			set {
				this.pds_msg_mvcelementnameField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_reqd {
			get {
				return this.pds_msg_reqdField;
			}
			set {
				this.pds_msg_reqdField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_businesskey {
			get {
				return this.pds_msg_businesskeyField;
			}
			set {
				this.pds_msg_businesskeyField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_alphanumeric {
			get {
				return this.pds_msg_alphanumericField;
			}
			set {
				this.pds_msg_alphanumericField = value;
			}
		}
		
		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value {get; set;}
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
	public partial class ExternalAlertEventCONTENTSUBDIVISION {
		
		private string pds_msg_lengthField;
		
		private string pds_msg_loopField;
		
		private string pds_msg_mvcelementnameField;
		
		private string pds_msg_reqdField;
		
		private string pds_msg_businesskeyField;
		
		private string pds_msg_alphanumericField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_length {
			get {
				return this.pds_msg_lengthField;
			}
			set {
				this.pds_msg_lengthField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_loop {
			get {
				return this.pds_msg_loopField;
			}
			set {
				this.pds_msg_loopField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_mvcelementname {
			get {
				return this.pds_msg_mvcelementnameField;
			}
			set {
				this.pds_msg_mvcelementnameField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_reqd {
			get {
				return this.pds_msg_reqdField;
			}
			set {
				this.pds_msg_reqdField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_businesskey {
			get {
				return this.pds_msg_businesskeyField;
			}
			set {
				this.pds_msg_businesskeyField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_alphanumeric {
			get {
				return this.pds_msg_alphanumericField;
			}
			set {
				this.pds_msg_alphanumericField = value;
			}
		}
		
		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value {get; set;}
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
	public partial class ExternalAlertEventCONTENTDIVISION {
		
		private string pds_msg_lengthField;
		
		private string pds_msg_loopField;
		
		private string pds_msg_mvcelementnameField;
		
		private string pds_msg_reqdField;
		
		private string pds_msg_businesskeyField;
		
		private string pds_msg_alphanumericField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_length {
			get {
				return this.pds_msg_lengthField;
			}
			set {
				this.pds_msg_lengthField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_loop {
			get {
				return this.pds_msg_loopField;
			}
			set {
				this.pds_msg_loopField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_mvcelementname {
			get {
				return this.pds_msg_mvcelementnameField;
			}
			set {
				this.pds_msg_mvcelementnameField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_reqd {
			get {
				return this.pds_msg_reqdField;
			}
			set {
				this.pds_msg_reqdField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_businesskey {
			get {
				return this.pds_msg_businesskeyField;
			}
			set {
				this.pds_msg_businesskeyField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_alphanumeric {
			get {
				return this.pds_msg_alphanumericField;
			}
			set {
				this.pds_msg_alphanumericField = value;
			}
		}
		
		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value {get; set;}
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
	public partial class ExternalAlertEventCONTENTDIRECTION {
		
		private string pds_msg_lengthField;
		
		private string pds_msg_loopField;
		
		private string pds_msg_mvcelementnameField;
		
		private string pds_msg_reqdField;
		
		private string pds_msg_businesskeyField;
		
		private string pds_msg_alphanumericField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_length {
			get {
				return this.pds_msg_lengthField;
			}
			set {
				this.pds_msg_lengthField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_loop {
			get {
				return this.pds_msg_loopField;
			}
			set {
				this.pds_msg_loopField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_mvcelementname {
			get {
				return this.pds_msg_mvcelementnameField;
			}
			set {
				this.pds_msg_mvcelementnameField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_reqd {
			get {
				return this.pds_msg_reqdField;
			}
			set {
				this.pds_msg_reqdField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_businesskey {
			get {
				return this.pds_msg_businesskeyField;
			}
			set {
				this.pds_msg_businesskeyField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_alphanumeric {
			get {
				return this.pds_msg_alphanumericField;
			}
			set {
				this.pds_msg_alphanumericField = value;
			}
		}
		
		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value {get; set;}
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
	public partial class ExternalAlertEventCONTENTSTART_DATE {
		
		private string pds_msg_lengthField;
		
		private string pds_msg_loopField;
		
		private string pds_msg_mvcelementnameField;
		
		private string pds_msg_reqdField;
		
		private string pds_msg_businesskeyField;
		
		private string pds_msg_alphanumericField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_length {
			get {
				return this.pds_msg_lengthField;
			}
			set {
				this.pds_msg_lengthField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_loop {
			get {
				return this.pds_msg_loopField;
			}
			set {
				this.pds_msg_loopField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_mvcelementname {
			get {
				return this.pds_msg_mvcelementnameField;
			}
			set {
				this.pds_msg_mvcelementnameField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_reqd {
			get {
				return this.pds_msg_reqdField;
			}
			set {
				this.pds_msg_reqdField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_businesskey {
			get {
				return this.pds_msg_businesskeyField;
			}
			set {
				this.pds_msg_businesskeyField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_alphanumeric {
			get {
				return this.pds_msg_alphanumericField;
			}
			set {
				this.pds_msg_alphanumericField = value;
			}
		}
		
		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value {get; set;}
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
	public partial class ExternalAlertEventCONTENTSTART_TIME {
		
		private string pds_msg_lengthField;
		
		private string pds_msg_loopField;
		
		private string pds_msg_mvcelementnameField;
		
		private string pds_msg_reqdField;
		
		private string pds_msg_businesskeyField;
		
		private string pds_msg_alphanumericField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_length {
			get {
				return this.pds_msg_lengthField;
			}
			set {
				this.pds_msg_lengthField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_loop {
			get {
				return this.pds_msg_loopField;
			}
			set {
				this.pds_msg_loopField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_mvcelementname {
			get {
				return this.pds_msg_mvcelementnameField;
			}
			set {
				this.pds_msg_mvcelementnameField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_reqd {
			get {
				return this.pds_msg_reqdField;
			}
			set {
				this.pds_msg_reqdField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_businesskey {
			get {
				return this.pds_msg_businesskeyField;
			}
			set {
				this.pds_msg_businesskeyField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_alphanumeric {
			get {
				return this.pds_msg_alphanumericField;
			}
			set {
				this.pds_msg_alphanumericField = value;
			}
		}
		
		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value {get; set;}
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
	public partial class ExternalAlertEventCONTENTSTART_TIME_ZONE {
		
		private string pds_msg_lengthField;
		
		private string pds_msg_loopField;
		
		private string pds_msg_mvcelementnameField;
		
		private string pds_msg_reqdField;
		
		private string pds_msg_businesskeyField;
		
		private string pds_msg_alphanumericField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_length {
			get {
				return this.pds_msg_lengthField;
			}
			set {
				this.pds_msg_lengthField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_loop {
			get {
				return this.pds_msg_loopField;
			}
			set {
				this.pds_msg_loopField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_mvcelementname {
			get {
				return this.pds_msg_mvcelementnameField;
			}
			set {
				this.pds_msg_mvcelementnameField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_reqd {
			get {
				return this.pds_msg_reqdField;
			}
			set {
				this.pds_msg_reqdField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_businesskey {
			get {
				return this.pds_msg_businesskeyField;
			}
			set {
				this.pds_msg_businesskeyField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_alphanumeric {
			get {
				return this.pds_msg_alphanumericField;
			}
			set {
				this.pds_msg_alphanumericField = value;
			}
		}
		
		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value {get; set;}
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
	public partial class ExternalAlertEventCONTENTMESSAGE_TEXT {
		
		private string pds_msg_lengthField;
		
		private string pds_msg_loopField;
		
		private string pds_msg_mvcelementnameField;
		
		private string pds_msg_reqdField;
		
		private string pds_msg_businesskeyField;
		
		private string pds_msg_alphanumericField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_length {
			get {
				return this.pds_msg_lengthField;
			}
			set {
				this.pds_msg_lengthField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_loop {
			get {
				return this.pds_msg_loopField;
			}
			set {
				this.pds_msg_loopField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_mvcelementname {
			get {
				return this.pds_msg_mvcelementnameField;
			}
			set {
				this.pds_msg_mvcelementnameField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_reqd {
			get {
				return this.pds_msg_reqdField;
			}
			set {
				this.pds_msg_reqdField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_businesskey {
			get {
				return this.pds_msg_businesskeyField;
			}
			set {
				this.pds_msg_businesskeyField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_alphanumeric {
			get {
				return this.pds_msg_alphanumericField;
			}
			set {
				this.pds_msg_alphanumericField = value;
			}
		}
		
		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value {get; set;}
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
	public partial class ExternalAlertEventHEADER {
		
		private ExternalAlertEventHEADERPROTOCOLID[] pROTOCOLIDField;
		
		private ExternalAlertEventHEADERMSGID[] mSGIDField;
		
		private ExternalAlertEventHEADERTRACE_ID[] tRACE_IDField;
		
		private ExternalAlertEventHEADERMESSAGE_VERSION[] mESSAGE_VERSIONField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("PROTOCOLID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public ExternalAlertEventHEADERPROTOCOLID[] PROTOCOLID {
			get {
				return this.pROTOCOLIDField;
			}
			set {
				this.pROTOCOLIDField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("MSGID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public ExternalAlertEventHEADERMSGID[] MSGID {
			get {
				return this.mSGIDField;
			}
			set {
				this.mSGIDField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("TRACE_ID", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public ExternalAlertEventHEADERTRACE_ID[] TRACE_ID {
			get {
				return this.tRACE_IDField;
			}
			set {
				this.tRACE_IDField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlElementAttribute("MESSAGE_VERSION", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
		public ExternalAlertEventHEADERMESSAGE_VERSION[] MESSAGE_VERSION {
			get {
				return this.mESSAGE_VERSIONField;
			}
			set {
				this.mESSAGE_VERSIONField = value;
			}
		}
		
		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value {get; set;}
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
	public partial class ExternalAlertEventHEADERPROTOCOLID {
		
		private string pds_msg_lengthField;
		
		private string pds_msg_mvcelementnameField;
		
		private string pds_msg_reqdField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_length {
			get {
				return this.pds_msg_lengthField;
			}
			set {
				this.pds_msg_lengthField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_mvcelementname {
			get {
				return this.pds_msg_mvcelementnameField;
			}
			set {
				this.pds_msg_mvcelementnameField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_reqd {
			get {
				return this.pds_msg_reqdField;
			}
			set {
				this.pds_msg_reqdField = value;
			}
		}
		
		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value {get; set;}
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
	public partial class ExternalAlertEventHEADERMSGID {
		
		private string pds_msg_lengthField;
		
		private string pds_msg_mvcelementnameField;
		
		private string pds_msg_reqdField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_length {
			get {
				return this.pds_msg_lengthField;
			}
			set {
				this.pds_msg_lengthField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_mvcelementname {
			get {
				return this.pds_msg_mvcelementnameField;
			}
			set {
				this.pds_msg_mvcelementnameField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_reqd {
			get {
				return this.pds_msg_reqdField;
			}
			set {
				this.pds_msg_reqdField = value;
			}
		}
		
		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value {get; set;}
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
	public partial class ExternalAlertEventHEADERTRACE_ID {
		
		private string pds_msg_lengthField;
		
		private string pds_msg_mvcelementnameField;
		
		private string pds_msg_reqdField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_length {
			get {
				return this.pds_msg_lengthField;
			}
			set {
				this.pds_msg_lengthField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_mvcelementname {
			get {
				return this.pds_msg_mvcelementnameField;
			}
			set {
				this.pds_msg_mvcelementnameField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_reqd {
			get {
				return this.pds_msg_reqdField;
			}
			set {
				this.pds_msg_reqdField = value;
			}
		}
		
		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value {get; set;}
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
	public partial class ExternalAlertEventHEADERMESSAGE_VERSION {
		
		private string pds_msg_lengthField;
		
		private string pds_msg_mvcelementnameField;
		
		private string pds_msg_reqdField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_length {
			get {
				return this.pds_msg_lengthField;
			}
			set {
				this.pds_msg_lengthField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_mvcelementname {
			get {
				return this.pds_msg_mvcelementnameField;
			}
			set {
				this.pds_msg_mvcelementnameField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_reqd {
			get {
				return this.pds_msg_reqdField;
			}
			set {
				this.pds_msg_reqdField = value;
			}
		}
		
		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value {get; set;}
	}
	
	/// <remarks/>
	[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.7.2556.0")]
	[System.SerializableAttribute()]
	[System.Diagnostics.DebuggerStepThroughAttribute()]
	[System.ComponentModel.DesignerCategoryAttribute("code")]
	[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
	public partial class ExternalAlertEventMSGINFO {
		
		private string pds_msg_delimiterField;
		
		private string pds_msg_msgtypeField;
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_delimiter {
			get {
				return this.pds_msg_delimiterField;
			}
			set {
				this.pds_msg_delimiterField = value;
			}
		}
		
		/// <remarks/>
		[System.Xml.Serialization.XmlAttributeAttribute()]
		public string pds_msg_msgtype {
			get {
				return this.pds_msg_msgtypeField;
			}
			set {
				this.pds_msg_msgtypeField = value;
			}
		}
		
		[System.Xml.Serialization.XmlTextAttribute()]
		public string Value {get; set;}
	}
}